// Code generated by protoc-gen-go.
// source: gate.proto
// DO NOT EDIT!

package meta

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UserFindUserRequest struct {
	User string `protobuf:"bytes,1,opt,name=User,json=user" json:"User,omitempty"`
}

func (m *UserFindUserRequest) Reset()                    { *m = UserFindUserRequest{} }
func (m *UserFindUserRequest) String() string            { return proto.CompactTextString(m) }
func (*UserFindUserRequest) ProtoMessage()               {}
func (*UserFindUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type UserFindUserResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ID     int64           `protobuf:"varint,2,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *UserFindUserResponse) Reset()                    { *m = UserFindUserResponse{} }
func (m *UserFindUserResponse) String() string            { return proto.CompactTextString(m) }
func (*UserFindUserResponse) ProtoMessage()               {}
func (*UserFindUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *UserFindUserResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type UserAddFriendRequest struct {
	UserID  int64 `protobuf:"varint,1,opt,name=UserID,json=userID" json:"UserID,omitempty"`
	Confirm bool  `protobuf:"varint,2,opt,name=Confirm,json=confirm" json:"Confirm,omitempty"`
}

func (m *UserAddFriendRequest) Reset()                    { *m = UserAddFriendRequest{} }
func (m *UserAddFriendRequest) String() string            { return proto.CompactTextString(m) }
func (*UserAddFriendRequest) ProtoMessage()               {}
func (*UserAddFriendRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type UserAddFriendResponse struct {
	Header  *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Confirm bool            `protobuf:"varint,2,opt,name=Confirm,json=confirm" json:"Confirm,omitempty"`
}

func (m *UserAddFriendResponse) Reset()                    { *m = UserAddFriendResponse{} }
func (m *UserAddFriendResponse) String() string            { return proto.CompactTextString(m) }
func (*UserAddFriendResponse) ProtoMessage()               {}
func (*UserAddFriendResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *UserAddFriendResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type UserCreateGroupRequest struct {
}

func (m *UserCreateGroupRequest) Reset()                    { *m = UserCreateGroupRequest{} }
func (m *UserCreateGroupRequest) String() string            { return proto.CompactTextString(m) }
func (*UserCreateGroupRequest) ProtoMessage()               {}
func (*UserCreateGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type UserCreateGroupResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ID     int64           `protobuf:"varint,2,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *UserCreateGroupResponse) Reset()                    { *m = UserCreateGroupResponse{} }
func (m *UserCreateGroupResponse) String() string            { return proto.CompactTextString(m) }
func (*UserCreateGroupResponse) ProtoMessage()               {}
func (*UserCreateGroupResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *UserCreateGroupResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type UserRegisterRequest struct {
	User     string `protobuf:"bytes,1,opt,name=User,json=user" json:"User,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,json=password" json:"Password,omitempty"`
}

func (m *UserRegisterRequest) Reset()                    { *m = UserRegisterRequest{} }
func (m *UserRegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*UserRegisterRequest) ProtoMessage()               {}
func (*UserRegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

type UserRegisterResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ID     int64           `protobuf:"varint,2,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *UserRegisterResponse) Reset()                    { *m = UserRegisterResponse{} }
func (m *UserRegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*UserRegisterResponse) ProtoMessage()               {}
func (*UserRegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *UserRegisterResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type UpdateUserInfoRequest struct {
	Nickname string `protobuf:"bytes,1,opt,name=Nickname,json=nickname" json:"Nickname,omitempty"`
	Avatar   []byte `protobuf:"bytes,2,opt,name=Avatar,json=avatar,proto3" json:"Avatar,omitempty"`
}

func (m *UpdateUserInfoRequest) Reset()                    { *m = UpdateUserInfoRequest{} }
func (m *UpdateUserInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserInfoRequest) ProtoMessage()               {}
func (*UpdateUserInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

type UpdateUserInfoResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *UpdateUserInfoResponse) Reset()                    { *m = UpdateUserInfoResponse{} }
func (m *UpdateUserInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserInfoResponse) ProtoMessage()               {}
func (*UpdateUserInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *UpdateUserInfoResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type HeartbeatRequest struct {
}

func (m *HeartbeatRequest) Reset()                    { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()               {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

type HeartbeatResponse struct {
}

func (m *HeartbeatResponse) Reset()                    { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()               {}
func (*HeartbeatResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

type UserLoginRequest struct {
	User     string `protobuf:"bytes,1,opt,name=User,json=user" json:"User,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,json=password" json:"Password,omitempty"`
}

func (m *UserLoginRequest) Reset()                    { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()               {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

type UserLoginResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ID     int64           `protobuf:"varint,2,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *UserLoginResponse) Reset()                    { *m = UserLoginResponse{} }
func (m *UserLoginResponse) String() string            { return proto.CompactTextString(m) }
func (*UserLoginResponse) ProtoMessage()               {}
func (*UserLoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *UserLoginResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type UserLogoutRequest struct {
}

func (m *UserLogoutRequest) Reset()                    { *m = UserLogoutRequest{} }
func (m *UserLogoutRequest) String() string            { return proto.CompactTextString(m) }
func (*UserLogoutRequest) ProtoMessage()               {}
func (*UserLogoutRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

type UserLogoutResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *UserLogoutResponse) Reset()                    { *m = UserLogoutResponse{} }
func (m *UserLogoutResponse) String() string            { return proto.CompactTextString(m) }
func (*UserLogoutResponse) ProtoMessage()               {}
func (*UserLogoutResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *UserLogoutResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type SendMessageRequest struct {
	Msg *Message `protobuf:"bytes,1,opt,name=Msg,json=msg" json:"Msg,omitempty"`
}

func (m *SendMessageRequest) Reset()                    { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()               {}
func (*SendMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *SendMessageRequest) GetMsg() *Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

type SendMessageResponse struct {
	Header    *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	MessageID int64           `protobuf:"varint,2,opt,name=MessageID,json=messageID" json:"MessageID,omitempty"`
}

func (m *SendMessageResponse) Reset()                    { *m = SendMessageResponse{} }
func (m *SendMessageResponse) String() string            { return proto.CompactTextString(m) }
func (*SendMessageResponse) ProtoMessage()               {}
func (*SendMessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *SendMessageResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type RecvMessageRequest struct {
	LastMessageID int64 `protobuf:"varint,1,opt,name=LastMessageID,json=lastMessageID" json:"LastMessageID,omitempty"`
}

func (m *RecvMessageRequest) Reset()                    { *m = RecvMessageRequest{} }
func (m *RecvMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*RecvMessageRequest) ProtoMessage()               {}
func (*RecvMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

type RecvMessageResponse struct {
	MsgList []*Message `protobuf:"bytes,1,rep,name=MsgList,json=msgList" json:"MsgList,omitempty"`
}

func (m *RecvMessageResponse) Reset()                    { *m = RecvMessageResponse{} }
func (m *RecvMessageResponse) String() string            { return proto.CompactTextString(m) }
func (*RecvMessageResponse) ProtoMessage()               {}
func (*RecvMessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

func (m *RecvMessageResponse) GetMsgList() []*Message {
	if m != nil {
		return m.MsgList
	}
	return nil
}

type UserMessageList struct {
	MsgList []*Message `protobuf:"bytes,1,rep,name=MsgList,json=msgList" json:"MsgList,omitempty"`
}

func (m *UserMessageList) Reset()                    { *m = UserMessageList{} }
func (m *UserMessageList) String() string            { return proto.CompactTextString(m) }
func (*UserMessageList) ProtoMessage()               {}
func (*UserMessageList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

func (m *UserMessageList) GetMsgList() []*Message {
	if m != nil {
		return m.MsgList
	}
	return nil
}

type UploadImageRequest struct {
	Image []byte `protobuf:"bytes,1,opt,name=Image,json=image,proto3" json:"Image,omitempty"`
}

func (m *UploadImageRequest) Reset()                    { *m = UploadImageRequest{} }
func (m *UploadImageRequest) String() string            { return proto.CompactTextString(m) }
func (*UploadImageRequest) ProtoMessage()               {}
func (*UploadImageRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{21} }

type UploadImageResponse struct {
	Header  *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ImageID int64           `protobuf:"varint,2,opt,name=ImageID,json=imageID" json:"ImageID,omitempty"`
}

func (m *UploadImageResponse) Reset()                    { *m = UploadImageResponse{} }
func (m *UploadImageResponse) String() string            { return proto.CompactTextString(m) }
func (*UploadImageResponse) ProtoMessage()               {}
func (*UploadImageResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{22} }

func (m *UploadImageResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type DownloadImageRequest struct {
	ImageID []int64 `protobuf:"varint,1,rep,packed,name=ImageID,json=imageID" json:"ImageID,omitempty"`
}

func (m *DownloadImageRequest) Reset()                    { *m = DownloadImageRequest{} }
func (m *DownloadImageRequest) String() string            { return proto.CompactTextString(m) }
func (*DownloadImageRequest) ProtoMessage()               {}
func (*DownloadImageRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{23} }

type DownloadImageResponse struct {
	Image [][]byte `protobuf:"bytes,1,rep,name=Image,json=image,proto3" json:"Image,omitempty"`
}

func (m *DownloadImageResponse) Reset()                    { *m = DownloadImageResponse{} }
func (m *DownloadImageResponse) String() string            { return proto.CompactTextString(m) }
func (*DownloadImageResponse) ProtoMessage()               {}
func (*DownloadImageResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{24} }

type NoticeRequest struct {
	ChannelID int64    `protobuf:"varint,1,opt,name=ChannelID,json=channelID" json:"ChannelID,omitempty"`
	Msg       *Message `protobuf:"bytes,2,opt,name=Msg,json=msg" json:"Msg,omitempty"`
}

func (m *NoticeRequest) Reset()                    { *m = NoticeRequest{} }
func (m *NoticeRequest) String() string            { return proto.CompactTextString(m) }
func (*NoticeRequest) ProtoMessage()               {}
func (*NoticeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{25} }

func (m *NoticeRequest) GetMsg() *Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

type NoticeResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *NoticeResponse) Reset()                    { *m = NoticeResponse{} }
func (m *NoticeResponse) String() string            { return proto.CompactTextString(m) }
func (*NoticeResponse) ProtoMessage()               {}
func (*NoticeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{26} }

func (m *NoticeResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*UserFindUserRequest)(nil), "candy.meta.UserFindUserRequest")
	proto.RegisterType((*UserFindUserResponse)(nil), "candy.meta.UserFindUserResponse")
	proto.RegisterType((*UserAddFriendRequest)(nil), "candy.meta.UserAddFriendRequest")
	proto.RegisterType((*UserAddFriendResponse)(nil), "candy.meta.UserAddFriendResponse")
	proto.RegisterType((*UserCreateGroupRequest)(nil), "candy.meta.UserCreateGroupRequest")
	proto.RegisterType((*UserCreateGroupResponse)(nil), "candy.meta.UserCreateGroupResponse")
	proto.RegisterType((*UserRegisterRequest)(nil), "candy.meta.UserRegisterRequest")
	proto.RegisterType((*UserRegisterResponse)(nil), "candy.meta.UserRegisterResponse")
	proto.RegisterType((*UpdateUserInfoRequest)(nil), "candy.meta.UpdateUserInfoRequest")
	proto.RegisterType((*UpdateUserInfoResponse)(nil), "candy.meta.UpdateUserInfoResponse")
	proto.RegisterType((*HeartbeatRequest)(nil), "candy.meta.HeartbeatRequest")
	proto.RegisterType((*HeartbeatResponse)(nil), "candy.meta.HeartbeatResponse")
	proto.RegisterType((*UserLoginRequest)(nil), "candy.meta.UserLoginRequest")
	proto.RegisterType((*UserLoginResponse)(nil), "candy.meta.UserLoginResponse")
	proto.RegisterType((*UserLogoutRequest)(nil), "candy.meta.UserLogoutRequest")
	proto.RegisterType((*UserLogoutResponse)(nil), "candy.meta.UserLogoutResponse")
	proto.RegisterType((*SendMessageRequest)(nil), "candy.meta.SendMessageRequest")
	proto.RegisterType((*SendMessageResponse)(nil), "candy.meta.SendMessageResponse")
	proto.RegisterType((*RecvMessageRequest)(nil), "candy.meta.RecvMessageRequest")
	proto.RegisterType((*RecvMessageResponse)(nil), "candy.meta.RecvMessageResponse")
	proto.RegisterType((*UserMessageList)(nil), "candy.meta.UserMessageList")
	proto.RegisterType((*UploadImageRequest)(nil), "candy.meta.UploadImageRequest")
	proto.RegisterType((*UploadImageResponse)(nil), "candy.meta.UploadImageResponse")
	proto.RegisterType((*DownloadImageRequest)(nil), "candy.meta.DownloadImageRequest")
	proto.RegisterType((*DownloadImageResponse)(nil), "candy.meta.DownloadImageResponse")
	proto.RegisterType((*NoticeRequest)(nil), "candy.meta.NoticeRequest")
	proto.RegisterType((*NoticeResponse)(nil), "candy.meta.NoticeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Gate service

type GateClient interface {
	Register(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*UserRegisterResponse, error)
	UpdateUserInfo(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*UpdateUserInfoResponse, error)
	Login(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error)
	Logout(ctx context.Context, in *UserLogoutRequest, opts ...grpc.CallOption) (*UserLoginResponse, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	RecvMessage(ctx context.Context, in *RecvMessageRequest, opts ...grpc.CallOption) (*RecvMessageResponse, error)
	// AddFriend 添加好友或确认接受添加.
	AddFriend(ctx context.Context, in *UserAddFriendRequest, opts ...grpc.CallOption) (*UserAddFriendResponse, error)
	// FindUser 添加好友前先查找出来对应的ID.
	FindUser(ctx context.Context, in *UserFindUserRequest, opts ...grpc.CallOption) (*UserFindUserResponse, error)
	CreateGroup(ctx context.Context, in *UserCreateGroupRequest, opts ...grpc.CallOption) (*UserCreateGroupResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	UploadImage(ctx context.Context, in *UploadImageRequest, opts ...grpc.CallOption) (*UploadImageResponse, error)
	DownloadImage(ctx context.Context, in *DownloadImageRequest, opts ...grpc.CallOption) (*DownloadImageResponse, error)
	// server interface.
	Notice(ctx context.Context, in *NoticeRequest, opts ...grpc.CallOption) (*NoticeResponse, error)
}

type gateClient struct {
	cc *grpc.ClientConn
}

func NewGateClient(cc *grpc.ClientConn) GateClient {
	return &gateClient{cc}
}

func (c *gateClient) Register(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*UserRegisterResponse, error) {
	out := new(UserRegisterResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*UpdateUserInfoResponse, error) {
	out := new(UpdateUserInfoResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/UpdateUserInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) Login(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error) {
	out := new(UserLoginResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) Logout(ctx context.Context, in *UserLogoutRequest, opts ...grpc.CallOption) (*UserLoginResponse, error) {
	out := new(UserLoginResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/Logout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	out := new(SendMessageResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/SendMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) RecvMessage(ctx context.Context, in *RecvMessageRequest, opts ...grpc.CallOption) (*RecvMessageResponse, error) {
	out := new(RecvMessageResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/RecvMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) AddFriend(ctx context.Context, in *UserAddFriendRequest, opts ...grpc.CallOption) (*UserAddFriendResponse, error) {
	out := new(UserAddFriendResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/AddFriend", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) FindUser(ctx context.Context, in *UserFindUserRequest, opts ...grpc.CallOption) (*UserFindUserResponse, error) {
	out := new(UserFindUserResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/FindUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) CreateGroup(ctx context.Context, in *UserCreateGroupRequest, opts ...grpc.CallOption) (*UserCreateGroupResponse, error) {
	out := new(UserCreateGroupResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/CreateGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/Heartbeat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) UploadImage(ctx context.Context, in *UploadImageRequest, opts ...grpc.CallOption) (*UploadImageResponse, error) {
	out := new(UploadImageResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/UploadImage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) DownloadImage(ctx context.Context, in *DownloadImageRequest, opts ...grpc.CallOption) (*DownloadImageResponse, error) {
	out := new(DownloadImageResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/DownloadImage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) Notice(ctx context.Context, in *NoticeRequest, opts ...grpc.CallOption) (*NoticeResponse, error) {
	out := new(NoticeResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/Notice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Gate service

type GateServer interface {
	Register(context.Context, *UserRegisterRequest) (*UserRegisterResponse, error)
	UpdateUserInfo(context.Context, *UpdateUserInfoRequest) (*UpdateUserInfoResponse, error)
	Login(context.Context, *UserLoginRequest) (*UserLoginResponse, error)
	Logout(context.Context, *UserLogoutRequest) (*UserLoginResponse, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	RecvMessage(context.Context, *RecvMessageRequest) (*RecvMessageResponse, error)
	// AddFriend 添加好友或确认接受添加.
	AddFriend(context.Context, *UserAddFriendRequest) (*UserAddFriendResponse, error)
	// FindUser 添加好友前先查找出来对应的ID.
	FindUser(context.Context, *UserFindUserRequest) (*UserFindUserResponse, error)
	CreateGroup(context.Context, *UserCreateGroupRequest) (*UserCreateGroupResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	UploadImage(context.Context, *UploadImageRequest) (*UploadImageResponse, error)
	DownloadImage(context.Context, *DownloadImageRequest) (*DownloadImageResponse, error)
	// server interface.
	Notice(context.Context, *NoticeRequest) (*NoticeResponse, error)
}

func RegisterGateServer(s *grpc.Server, srv GateServer) {
	s.RegisterService(&_Gate_serviceDesc, srv)
}

func _Gate_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).Register(ctx, req.(*UserRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_UpdateUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).UpdateUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/UpdateUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).UpdateUserInfo(ctx, req.(*UpdateUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).Login(ctx, req.(*UserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).Logout(ctx, req.(*UserLogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_RecvMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecvMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).RecvMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/RecvMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).RecvMessage(ctx, req.(*RecvMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_AddFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAddFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).AddFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/AddFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).AddFriend(ctx, req.(*UserAddFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_FindUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFindUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).FindUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/FindUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).FindUser(ctx, req.(*UserFindUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).CreateGroup(ctx, req.(*UserCreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_UploadImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).UploadImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/UploadImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).UploadImage(ctx, req.(*UploadImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_DownloadImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).DownloadImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/DownloadImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).DownloadImage(ctx, req.(*DownloadImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_Notice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).Notice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/Notice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).Notice(ctx, req.(*NoticeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "candy.meta.Gate",
	HandlerType: (*GateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Gate_Register_Handler,
		},
		{
			MethodName: "UpdateUserInfo",
			Handler:    _Gate_UpdateUserInfo_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Gate_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Gate_Logout_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _Gate_SendMessage_Handler,
		},
		{
			MethodName: "RecvMessage",
			Handler:    _Gate_RecvMessage_Handler,
		},
		{
			MethodName: "AddFriend",
			Handler:    _Gate_AddFriend_Handler,
		},
		{
			MethodName: "FindUser",
			Handler:    _Gate_FindUser_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _Gate_CreateGroup_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Gate_Heartbeat_Handler,
		},
		{
			MethodName: "UploadImage",
			Handler:    _Gate_UploadImage_Handler,
		},
		{
			MethodName: "DownloadImage",
			Handler:    _Gate_DownloadImage_Handler,
		},
		{
			MethodName: "Notice",
			Handler:    _Gate_Notice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor1,
}

func init() { proto.RegisterFile("gate.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 799 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x56, 0xdf, 0x4f, 0xdb, 0x48,
	0x10, 0x56, 0x7e, 0xe0, 0xd8, 0x03, 0xe1, 0x60, 0x03, 0x5c, 0xce, 0xe2, 0x8e, 0xb0, 0xd7, 0x4a,
	0xb4, 0x12, 0x51, 0x45, 0xdf, 0xda, 0x87, 0x16, 0x48, 0x21, 0xa8, 0x09, 0x42, 0x2e, 0x14, 0x09,
	0xa9, 0x0f, 0x8b, 0xbd, 0x18, 0xab, 0xd8, 0x4e, 0xbd, 0x0e, 0xa8, 0xff, 0x40, 0xff, 0xee, 0xca,
	0xf6, 0xda, 0xd9, 0xb5, 0x9d, 0xa0, 0x12, 0x9e, 0xac, 0x99, 0xfd, 0xe6, 0xdb, 0x99, 0x9d, 0xdd,
	0xcf, 0x03, 0x60, 0x93, 0x90, 0x76, 0x47, 0x81, 0x1f, 0xfa, 0x08, 0x4c, 0xe2, 0x59, 0x3f, 0xbb,
	0x2e, 0x0d, 0x89, 0xbe, 0x64, 0xfa, 0xae, 0xeb, 0x7b, 0xc9, 0x0a, 0x7e, 0x05, 0xad, 0x0b, 0x46,
	0x83, 0x23, 0xc7, 0xb3, 0xa2, 0xaf, 0x41, 0x7f, 0x8c, 0x29, 0x0b, 0x11, 0x82, 0x7a, 0x64, 0xb6,
	0x2b, 0x9d, 0xca, 0x8e, 0x66, 0xd4, 0xc7, 0x8c, 0x06, 0xf8, 0x0a, 0xd6, 0x64, 0x28, 0x1b, 0xf9,
	0x1e, 0xa3, 0x68, 0x0f, 0x94, 0x5b, 0x4a, 0x2c, 0x8e, 0x5e, 0xdc, 0xd3, 0xbb, 0x93, 0xdd, 0xba,
	0x29, 0xaa, 0x1f, 0x23, 0x0c, 0x8e, 0x44, 0xcb, 0x50, 0x3d, 0xe9, 0xb5, 0xab, 0x9d, 0xca, 0x4e,
	0xcd, 0xa8, 0x3a, 0x3d, 0xdc, 0x4f, 0xb8, 0xf7, 0x2d, 0xeb, 0x28, 0x70, 0xa8, 0x67, 0xa5, 0x79,
	0x6c, 0x80, 0x12, 0xf9, 0x4f, 0x7a, 0x31, 0x77, 0xcd, 0x50, 0xc6, 0xb1, 0x85, 0xda, 0xd0, 0x38,
	0xf4, 0xbd, 0x1b, 0x27, 0x70, 0x63, 0x12, 0xd5, 0x68, 0x98, 0x89, 0x89, 0x29, 0xac, 0xe7, 0x98,
	0xe6, 0x48, 0x73, 0xfa, 0x36, 0x6d, 0xd8, 0x88, 0xb6, 0x39, 0x0c, 0x28, 0x09, 0xe9, 0x71, 0xe0,
	0x8f, 0x47, 0x3c, 0x65, 0xfc, 0x0d, 0xfe, 0x2e, 0xac, 0x3c, 0xe3, 0x49, 0x7d, 0x4a, 0x1a, 0x66,
	0x50, 0xdb, 0x61, 0xe1, 0xcc, 0x86, 0x21, 0x1d, 0xd4, 0x33, 0xc2, 0xd8, 0x83, 0x1f, 0x58, 0x31,
	0x81, 0x66, 0xa8, 0x23, 0x6e, 0xa7, 0xcd, 0x9c, 0xd0, 0x3c, 0x63, 0x8a, 0x9f, 0x61, 0xfd, 0x62,
	0x64, 0x91, 0x90, 0xc6, 0xad, 0xf3, 0x6e, 0xfc, 0x34, 0x49, 0x1d, 0xd4, 0x53, 0xc7, 0xfc, 0xee,
	0x11, 0x97, 0xf2, 0x44, 0x55, 0x8f, 0xdb, 0x51, 0xa7, 0xf7, 0xef, 0x49, 0x48, 0x82, 0x98, 0x68,
	0xc9, 0x50, 0x48, 0x6c, 0xe1, 0x01, 0x6c, 0xe4, 0xc9, 0x9e, 0x9e, 0x2a, 0x46, 0xb0, 0xd2, 0xa7,
	0x24, 0x08, 0xaf, 0x29, 0x09, 0xd3, 0x86, 0xb5, 0x60, 0x55, 0xf0, 0x25, 0x61, 0xf8, 0x00, 0x56,
	0xa2, 0x0d, 0x07, 0xbe, 0xed, 0x78, 0x4f, 0x3d, 0xe3, 0x4b, 0x58, 0x15, 0x38, 0x9e, 0xf1, 0x80,
	0x5b, 0x19, 0xb1, 0x3f, 0xce, 0xca, 0xe8, 0x03, 0x12, 0x9d, 0x73, 0x1c, 0xd2, 0x7b, 0x40, 0x5f,
	0xa8, 0x67, 0x0d, 0x29, 0x63, 0xc4, 0xa6, 0x69, 0xf5, 0x2f, 0xa1, 0x36, 0x64, 0x36, 0xa7, 0x69,
	0x89, 0x34, 0x29, 0xb0, 0xe6, 0x32, 0x1b, 0xdb, 0xd0, 0x92, 0x82, 0xe7, 0x28, 0x7b, 0x13, 0x34,
	0x4e, 0x93, 0x55, 0xaf, 0xb9, 0xa9, 0x03, 0xbf, 0x03, 0x64, 0x50, 0xf3, 0x3e, 0x97, 0xe5, 0x0b,
	0x68, 0x0e, 0x08, 0x0b, 0x27, 0x71, 0x89, 0x6e, 0x34, 0xef, 0x44, 0x27, 0xee, 0x41, 0x4b, 0x8a,
	0xe5, 0x49, 0xee, 0x42, 0x63, 0xc8, 0xec, 0x81, 0xc3, 0xc2, 0x76, 0xa5, 0x53, 0x9b, 0x56, 0x66,
	0xc3, 0x4d, 0x30, 0xf8, 0x23, 0xfc, 0x15, 0x9d, 0x38, 0xf7, 0x47, 0xae, 0x3f, 0x65, 0x78, 0x0d,
	0xe8, 0x62, 0x74, 0xe7, 0x13, 0xeb, 0xc4, 0x15, 0x6a, 0x58, 0x83, 0x85, 0xd8, 0x8e, 0x73, 0x5f,
	0x32, 0x16, 0x9c, 0xc8, 0xc0, 0x26, 0xb4, 0x24, 0xec, 0x7c, 0xb2, 0x16, 0x93, 0x64, 0xc7, 0xda,
	0x70, 0x12, 0x13, 0xbf, 0x81, 0xb5, 0x9e, 0xff, 0xe0, 0x15, 0x52, 0x12, 0x22, 0xa2, 0xba, 0x84,
	0x88, 0x5d, 0x58, 0xcf, 0x45, 0xf0, 0xc4, 0x84, 0x2a, 0x6a, 0x93, 0x2a, 0xce, 0xa1, 0x79, 0xea,
	0x87, 0x8e, 0x99, 0x31, 0x6f, 0x82, 0x76, 0x78, 0x4b, 0x3c, 0x8f, 0xde, 0x65, 0xcd, 0xd2, 0xcc,
	0xd4, 0x91, 0x5e, 0xba, 0xea, 0x23, 0x97, 0xae, 0x07, 0xcb, 0x29, 0xeb, 0xd3, 0x8f, 0x65, 0xef,
	0x97, 0x0a, 0xf5, 0x63, 0x12, 0x52, 0x34, 0x04, 0x35, 0x15, 0x46, 0xb4, 0x25, 0x06, 0x96, 0x28,
	0xaf, 0xde, 0x99, 0x0e, 0xe0, 0xb9, 0x5c, 0xc2, 0xb2, 0x2c, 0x61, 0x68, 0x5b, 0x8a, 0x29, 0xd3,
	0x4a, 0x1d, 0xcf, 0x82, 0x70, 0xe2, 0x1e, 0x2c, 0xc4, 0xe2, 0x82, 0x36, 0xf3, 0x39, 0x88, 0xba,
	0xa5, 0xff, 0x3b, 0x65, 0x95, 0xb3, 0x1c, 0x81, 0x92, 0x88, 0x06, 0x2a, 0x03, 0x4e, 0x14, 0xe6,
	0x31, 0x9e, 0x53, 0x58, 0x14, 0x5e, 0x3e, 0xfa, 0x4f, 0x44, 0x17, 0xf5, 0x44, 0xdf, 0x9a, 0xba,
	0x3e, 0xe1, 0x13, 0x1e, 0xa9, 0xcc, 0x57, 0x7c, 0xf9, 0x32, 0x5f, 0xd9, 0xeb, 0x3e, 0x03, 0x2d,
	0x9b, 0x0a, 0x50, 0xa1, 0x6b, 0xf9, 0xd1, 0x43, 0xdf, 0x9e, 0x81, 0xe0, 0x8c, 0x43, 0x50, 0xd3,
	0x69, 0xa8, 0x78, 0x4f, 0x72, 0x23, 0x55, 0xf1, 0x9e, 0x14, 0x06, 0xa9, 0xaf, 0xb0, 0x28, 0x4c,
	0x0d, 0x08, 0xe7, 0x03, 0x8a, 0xc3, 0x86, 0xfe, 0xff, 0x4c, 0x0c, 0xe7, 0xed, 0x83, 0x96, 0xfd,
	0xe0, 0xe4, 0xab, 0x92, 0xff, 0x17, 0xca, 0x2d, 0x2e, 0xfc, 0x15, 0xa3, 0x96, 0x08, 0x1a, 0x24,
	0xb7, 0xa4, 0x28, 0x64, 0x72, 0x4b, 0xca, 0xc4, 0xeb, 0x1c, 0x9a, 0x92, 0x78, 0xc8, 0x6d, 0x29,
	0x53, 0x22, 0xb9, 0x2d, 0xe5, 0xca, 0xf3, 0x01, 0x94, 0x44, 0x0d, 0xd0, 0x3f, 0x22, 0x58, 0xd2,
	0x1d, 0x5d, 0x2f, 0x5b, 0x4a, 0x08, 0x0e, 0x94, 0xab, 0x7a, 0xe4, 0xbe, 0x56, 0xe2, 0x19, 0xf9,
	0xed, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x72, 0x47, 0xf1, 0xfc, 0x4b, 0x0b, 0x00, 0x00,
}
