// Code generated by protoc-gen-go.
// source: notice.proto
// DO NOT EDIT!

package meta

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SubscribeRequest struct {
	ID   int64  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Host string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
}

func (m *SubscribeRequest) Reset()                    { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()               {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type SubscribeResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *SubscribeResponse) Reset()                    { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string            { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()               {}
func (*SubscribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *SubscribeResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type UnsubscribeRequest struct {
	ID   int64  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Host string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
}

func (m *UnsubscribeRequest) Reset()                    { *m = UnsubscribeRequest{} }
func (m *UnsubscribeRequest) String() string            { return proto.CompactTextString(m) }
func (*UnsubscribeRequest) ProtoMessage()               {}
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

type UnsubscribeResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *UnsubscribeResponse) Reset()                    { *m = UnsubscribeResponse{} }
func (m *UnsubscribeResponse) String() string            { return proto.CompactTextString(m) }
func (*UnsubscribeResponse) ProtoMessage()               {}
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *UnsubscribeResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type PushRequest struct {
	ID  []int64  `protobuf:"varint,1,rep,packed,name=ID" json:"ID,omitempty"`
	Msg *Message `protobuf:"bytes,2,opt,name=Msg" json:"Msg,omitempty"`
}

func (m *PushRequest) Reset()                    { *m = PushRequest{} }
func (m *PushRequest) String() string            { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()               {}
func (*PushRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *PushRequest) GetMsg() *Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

type PushResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *PushResponse) Reset()                    { *m = PushResponse{} }
func (m *PushResponse) String() string            { return proto.CompactTextString(m) }
func (*PushResponse) ProtoMessage()               {}
func (*PushResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *PushResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*SubscribeRequest)(nil), "candy.meta.SubscribeRequest")
	proto.RegisterType((*SubscribeResponse)(nil), "candy.meta.SubscribeResponse")
	proto.RegisterType((*UnsubscribeRequest)(nil), "candy.meta.UnsubscribeRequest")
	proto.RegisterType((*UnsubscribeResponse)(nil), "candy.meta.UnsubscribeResponse")
	proto.RegisterType((*PushRequest)(nil), "candy.meta.PushRequest")
	proto.RegisterType((*PushResponse)(nil), "candy.meta.PushResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Notice service

type NoticeClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error)
	Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error)
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error)
}

type noticeClient struct {
	cc *grpc.ClientConn
}

func NewNoticeClient(cc *grpc.ClientConn) NoticeClient {
	return &noticeClient{cc}
}

func (c *noticeClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error) {
	out := new(SubscribeResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Notice/Subscribe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noticeClient) Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error) {
	out := new(UnsubscribeResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Notice/Unsubscribe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noticeClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error) {
	out := new(PushResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Notice/Push", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Notice service

type NoticeServer interface {
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error)
	Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeResponse, error)
	Push(context.Context, *PushRequest) (*PushResponse, error)
}

func RegisterNoticeServer(s *grpc.Server, srv NoticeServer) {
	s.RegisterService(&_Notice_serviceDesc, srv)
}

func _Notice_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Notice/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notice_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Notice/Unsubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeServer).Unsubscribe(ctx, req.(*UnsubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notice_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Notice/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notice_serviceDesc = grpc.ServiceDesc{
	ServiceName: "candy.meta.Notice",
	HandlerType: (*NoticeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _Notice_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _Notice_Unsubscribe_Handler,
		},
		{
			MethodName: "Push",
			Handler:    _Notice_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor3,
}

func init() { proto.RegisterFile("notice.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcb, 0x2f, 0xc9,
	0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0x4e, 0xcc, 0x4b, 0xa9, 0xd4,
	0xcb, 0x4d, 0x2d, 0x49, 0x94, 0xe2, 0x49, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x83, 0xc8, 0x28, 0xe9,
	0x70, 0x09, 0x04, 0x97, 0x26, 0x15, 0x27, 0x17, 0x65, 0x26, 0xa5, 0x06, 0xa5, 0x16, 0x96, 0xa6,
	0x16, 0x97, 0x08, 0x71, 0x71, 0x31, 0x79, 0xba, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x0b, 0xf1,
	0x70, 0xb1, 0x64, 0xe4, 0x17, 0x97, 0x48, 0x30, 0x01, 0x79, 0x9c, 0x4a, 0xf6, 0x5c, 0x82, 0x48,
	0xaa, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xb4, 0xb8, 0xd8, 0x32, 0x52, 0x13, 0x53, 0x52,
	0x8b, 0xc0, 0x5a, 0xb8, 0x8d, 0xa4, 0xf4, 0x10, 0xb6, 0xe9, 0xc1, 0x54, 0x79, 0x80, 0x55, 0x28,
	0xe9, 0x71, 0x09, 0x85, 0xe6, 0x15, 0x13, 0x6f, 0xa1, 0x23, 0x97, 0x30, 0x8a, 0x7a, 0x32, 0xac,
	0xb4, 0xe6, 0xe2, 0x0e, 0x28, 0x2d, 0xce, 0x40, 0xb7, 0x8b, 0x19, 0x68, 0x97, 0x02, 0x17, 0xb3,
	0x6f, 0x71, 0x3a, 0xd8, 0x2a, 0x6e, 0x23, 0x61, 0x64, 0x33, 0x7c, 0x53, 0x8b, 0x8b, 0x13, 0xd3,
	0x53, 0x95, 0xac, 0xb8, 0x78, 0x20, 0x9a, 0x49, 0xb7, 0xd8, 0xe8, 0x2e, 0x23, 0x17, 0x9b, 0x1f,
	0x38, 0x16, 0x84, 0x3c, 0xb8, 0x38, 0xe1, 0xe1, 0x26, 0x24, 0x83, 0xac, 0x07, 0x3d, 0xf0, 0xa5,
	0x64, 0x71, 0xc8, 0x42, 0x1d, 0xe0, 0xc7, 0xc5, 0x8d, 0x14, 0x20, 0x42, 0x72, 0xc8, 0xaa, 0x31,
	0x43, 0x56, 0x4a, 0x1e, 0xa7, 0x3c, 0xd4, 0x3c, 0x4b, 0x2e, 0x16, 0x90, 0x07, 0x85, 0xc4, 0x91,
	0x15, 0x22, 0x85, 0x97, 0x94, 0x04, 0xa6, 0x04, 0x44, 0xab, 0x13, 0x5b, 0x14, 0x0b, 0x48, 0x30,
	0x89, 0x0d, 0x9c, 0x92, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x9c, 0xc1, 0x5b, 0x73,
	0x02, 0x00, 0x00,
}
