// Code generated by protoc-gen-go.
// source: store.proto
// DO NOT EDIT!

package meta

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type StoreFindUserRequest struct {
	User string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *StoreFindUserRequest) Reset()                    { *m = StoreFindUserRequest{} }
func (m *StoreFindUserRequest) String() string            { return proto.CompactTextString(m) }
func (*StoreFindUserRequest) ProtoMessage()               {}
func (*StoreFindUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

type StoreFindUserResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Users  []string        `protobuf:"bytes,2,rep,name=users" json:"users,omitempty"`
}

func (m *StoreFindUserResponse) Reset()                    { *m = StoreFindUserResponse{} }
func (m *StoreFindUserResponse) String() string            { return proto.CompactTextString(m) }
func (*StoreFindUserResponse) ProtoMessage()               {}
func (*StoreFindUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *StoreFindUserResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type StoreAddFriendRequest struct {
	From  int64          `protobuf:"varint,1,opt,name=From" json:"From,omitempty"`
	To    int64          `protobuf:"varint,2,opt,name=To" json:"To,omitempty"`
	State FriendRelation `protobuf:"varint,3,opt,name=State,enum=candy.meta.FriendRelation" json:"State,omitempty"`
}

func (m *StoreAddFriendRequest) Reset()                    { *m = StoreAddFriendRequest{} }
func (m *StoreAddFriendRequest) String() string            { return proto.CompactTextString(m) }
func (*StoreAddFriendRequest) ProtoMessage()               {}
func (*StoreAddFriendRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

type StoreAddFriendResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	State  FriendRelation  `protobuf:"varint,2,opt,name=State,enum=candy.meta.FriendRelation" json:"State,omitempty"`
}

func (m *StoreAddFriendResponse) Reset()                    { *m = StoreAddFriendResponse{} }
func (m *StoreAddFriendResponse) String() string            { return proto.CompactTextString(m) }
func (*StoreAddFriendResponse) ProtoMessage()               {}
func (*StoreAddFriendResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *StoreAddFriendResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type StoreRegisterRequest struct {
	ID       int64  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	User     string `protobuf:"bytes,2,opt,name=User" json:"User,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=Password" json:"Password,omitempty"`
}

func (m *StoreRegisterRequest) Reset()                    { *m = StoreRegisterRequest{} }
func (m *StoreRegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*StoreRegisterRequest) ProtoMessage()               {}
func (*StoreRegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

type StoreRegisterResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *StoreRegisterResponse) Reset()                    { *m = StoreRegisterResponse{} }
func (m *StoreRegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*StoreRegisterResponse) ProtoMessage()               {}
func (*StoreRegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

func (m *StoreRegisterResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type StoreUpdateUserInfoRequest struct {
	User     string `protobuf:"bytes,1,opt,name=User" json:"User,omitempty"`
	NickName string `protobuf:"bytes,2,opt,name=NickName" json:"NickName,omitempty"`
	Avatar   []byte `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
}

func (m *StoreUpdateUserInfoRequest) Reset()                    { *m = StoreUpdateUserInfoRequest{} }
func (m *StoreUpdateUserInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*StoreUpdateUserInfoRequest) ProtoMessage()               {}
func (*StoreUpdateUserInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{6} }

type StoreUpdateUserInfoResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ID     int64           `protobuf:"varint,2,opt,name=ID" json:"ID,omitempty"`
}

func (m *StoreUpdateUserInfoResponse) Reset()                    { *m = StoreUpdateUserInfoResponse{} }
func (m *StoreUpdateUserInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*StoreUpdateUserInfoResponse) ProtoMessage()               {}
func (*StoreUpdateUserInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{7} }

func (m *StoreUpdateUserInfoResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type StoreUpdateUserPasswordRequest struct {
	User     string `protobuf:"bytes,1,opt,name=User" json:"User,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
}

func (m *StoreUpdateUserPasswordRequest) Reset()                    { *m = StoreUpdateUserPasswordRequest{} }
func (m *StoreUpdateUserPasswordRequest) String() string            { return proto.CompactTextString(m) }
func (*StoreUpdateUserPasswordRequest) ProtoMessage()               {}
func (*StoreUpdateUserPasswordRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{8} }

type StoreUpdateUserPasswordResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ID     int64           `protobuf:"varint,2,opt,name=ID" json:"ID,omitempty"`
}

func (m *StoreUpdateUserPasswordResponse) Reset()                    { *m = StoreUpdateUserPasswordResponse{} }
func (m *StoreUpdateUserPasswordResponse) String() string            { return proto.CompactTextString(m) }
func (*StoreUpdateUserPasswordResponse) ProtoMessage()               {}
func (*StoreUpdateUserPasswordResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{9} }

func (m *StoreUpdateUserPasswordResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type StoreGetUserInfoRequest struct {
	User string `protobuf:"bytes,1,opt,name=User" json:"User,omitempty"`
}

func (m *StoreGetUserInfoRequest) Reset()                    { *m = StoreGetUserInfoRequest{} }
func (m *StoreGetUserInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*StoreGetUserInfoRequest) ProtoMessage()               {}
func (*StoreGetUserInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{10} }

type StoreGetUserInfoResponse struct {
	Header   *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ID       int64           `protobuf:"varint,2,opt,name=ID" json:"ID,omitempty"`
	User     string          `protobuf:"bytes,3,opt,name=User" json:"User,omitempty"`
	NickName string          `protobuf:"bytes,4,opt,name=NickName" json:"NickName,omitempty"`
	Avatar   []byte          `protobuf:"bytes,5,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
}

func (m *StoreGetUserInfoResponse) Reset()                    { *m = StoreGetUserInfoResponse{} }
func (m *StoreGetUserInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*StoreGetUserInfoResponse) ProtoMessage()               {}
func (*StoreGetUserInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{11} }

func (m *StoreGetUserInfoResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type StoreAuthRequest struct {
	User     string `protobuf:"bytes,1,opt,name=User" json:"User,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
}

func (m *StoreAuthRequest) Reset()                    { *m = StoreAuthRequest{} }
func (m *StoreAuthRequest) String() string            { return proto.CompactTextString(m) }
func (*StoreAuthRequest) ProtoMessage()               {}
func (*StoreAuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{12} }

type StoreAuthResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ID     int64           `protobuf:"varint,2,opt,name=ID" json:"ID,omitempty"`
}

func (m *StoreAuthResponse) Reset()                    { *m = StoreAuthResponse{} }
func (m *StoreAuthResponse) String() string            { return proto.CompactTextString(m) }
func (*StoreAuthResponse) ProtoMessage()               {}
func (*StoreAuthResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{13} }

func (m *StoreAuthResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type StoreCreateGroupRequest struct {
	UserID  int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	GroupID int64 `protobuf:"varint,2,opt,name=GroupID" json:"GroupID,omitempty"`
}

func (m *StoreCreateGroupRequest) Reset()                    { *m = StoreCreateGroupRequest{} }
func (m *StoreCreateGroupRequest) String() string            { return proto.CompactTextString(m) }
func (*StoreCreateGroupRequest) ProtoMessage()               {}
func (*StoreCreateGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{14} }

type StoreCreateGroupResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *StoreCreateGroupResponse) Reset()                    { *m = StoreCreateGroupResponse{} }
func (m *StoreCreateGroupResponse) String() string            { return proto.CompactTextString(m) }
func (*StoreCreateGroupResponse) ProtoMessage()               {}
func (*StoreCreateGroupResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{15} }

func (m *StoreCreateGroupResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type StoreNewMessageRequest struct {
	Msg *Message `protobuf:"bytes,1,opt,name=Msg" json:"Msg,omitempty"`
}

func (m *StoreNewMessageRequest) Reset()                    { *m = StoreNewMessageRequest{} }
func (m *StoreNewMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*StoreNewMessageRequest) ProtoMessage()               {}
func (*StoreNewMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{16} }

func (m *StoreNewMessageRequest) GetMsg() *Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

type StoreNewMessageResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *StoreNewMessageResponse) Reset()                    { *m = StoreNewMessageResponse{} }
func (m *StoreNewMessageResponse) String() string            { return proto.CompactTextString(m) }
func (*StoreNewMessageResponse) ProtoMessage()               {}
func (*StoreNewMessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{17} }

func (m *StoreNewMessageResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type StoreUploadFileRequest struct {
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	File   []byte         `protobuf:"bytes,2,opt,name=File,proto3" json:"File,omitempty"`
}

func (m *StoreUploadFileRequest) Reset()                    { *m = StoreUploadFileRequest{} }
func (m *StoreUploadFileRequest) String() string            { return proto.CompactTextString(m) }
func (*StoreUploadFileRequest) ProtoMessage()               {}
func (*StoreUploadFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{18} }

func (m *StoreUploadFileRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type StoreUploadFileResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *StoreUploadFileResponse) Reset()                    { *m = StoreUploadFileResponse{} }
func (m *StoreUploadFileResponse) String() string            { return proto.CompactTextString(m) }
func (*StoreUploadFileResponse) ProtoMessage()               {}
func (*StoreUploadFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{19} }

func (m *StoreUploadFileResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type StoreCheckFileRequest struct {
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Names  []string       `protobuf:"bytes,2,rep,name=Names" json:"Names,omitempty"`
}

func (m *StoreCheckFileRequest) Reset()                    { *m = StoreCheckFileRequest{} }
func (m *StoreCheckFileRequest) String() string            { return proto.CompactTextString(m) }
func (*StoreCheckFileRequest) ProtoMessage()               {}
func (*StoreCheckFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{20} }

func (m *StoreCheckFileRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type StoreCheckFileResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Names  []string        `protobuf:"bytes,2,rep,name=Names" json:"Names,omitempty"`
}

func (m *StoreCheckFileResponse) Reset()                    { *m = StoreCheckFileResponse{} }
func (m *StoreCheckFileResponse) String() string            { return proto.CompactTextString(m) }
func (*StoreCheckFileResponse) ProtoMessage()               {}
func (*StoreCheckFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{21} }

func (m *StoreCheckFileResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type StoreDownloadFileRequest struct {
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Names  []string       `protobuf:"bytes,2,rep,name=Names" json:"Names,omitempty"`
}

func (m *StoreDownloadFileRequest) Reset()                    { *m = StoreDownloadFileRequest{} }
func (m *StoreDownloadFileRequest) String() string            { return proto.CompactTextString(m) }
func (*StoreDownloadFileRequest) ProtoMessage()               {}
func (*StoreDownloadFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{22} }

func (m *StoreDownloadFileRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type StoreDownloadFileResponse struct {
	Header *ResponseHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Files  map[string][]byte `protobuf:"bytes,2,rep,name=Files" json:"Files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *StoreDownloadFileResponse) Reset()                    { *m = StoreDownloadFileResponse{} }
func (m *StoreDownloadFileResponse) String() string            { return proto.CompactTextString(m) }
func (*StoreDownloadFileResponse) ProtoMessage()               {}
func (*StoreDownloadFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{23} }

func (m *StoreDownloadFileResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *StoreDownloadFileResponse) GetFiles() map[string][]byte {
	if m != nil {
		return m.Files
	}
	return nil
}

type StoreSubscribeRequest struct {
	ID   int64  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Host string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
}

func (m *StoreSubscribeRequest) Reset()                    { *m = StoreSubscribeRequest{} }
func (m *StoreSubscribeRequest) String() string            { return proto.CompactTextString(m) }
func (*StoreSubscribeRequest) ProtoMessage()               {}
func (*StoreSubscribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{24} }

type StoreSubscribeResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *StoreSubscribeResponse) Reset()                    { *m = StoreSubscribeResponse{} }
func (m *StoreSubscribeResponse) String() string            { return proto.CompactTextString(m) }
func (*StoreSubscribeResponse) ProtoMessage()               {}
func (*StoreSubscribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{25} }

func (m *StoreSubscribeResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type StoreUnSubscribeRequest struct {
	ID   int64  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Host string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
}

func (m *StoreUnSubscribeRequest) Reset()                    { *m = StoreUnSubscribeRequest{} }
func (m *StoreUnSubscribeRequest) String() string            { return proto.CompactTextString(m) }
func (*StoreUnSubscribeRequest) ProtoMessage()               {}
func (*StoreUnSubscribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{26} }

type StoreUnSubscribeResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *StoreUnSubscribeResponse) Reset()                    { *m = StoreUnSubscribeResponse{} }
func (m *StoreUnSubscribeResponse) String() string            { return proto.CompactTextString(m) }
func (*StoreUnSubscribeResponse) ProtoMessage()               {}
func (*StoreUnSubscribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{27} }

func (m *StoreUnSubscribeResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*StoreFindUserRequest)(nil), "candy.meta.StoreFindUserRequest")
	proto.RegisterType((*StoreFindUserResponse)(nil), "candy.meta.StoreFindUserResponse")
	proto.RegisterType((*StoreAddFriendRequest)(nil), "candy.meta.StoreAddFriendRequest")
	proto.RegisterType((*StoreAddFriendResponse)(nil), "candy.meta.StoreAddFriendResponse")
	proto.RegisterType((*StoreRegisterRequest)(nil), "candy.meta.StoreRegisterRequest")
	proto.RegisterType((*StoreRegisterResponse)(nil), "candy.meta.StoreRegisterResponse")
	proto.RegisterType((*StoreUpdateUserInfoRequest)(nil), "candy.meta.StoreUpdateUserInfoRequest")
	proto.RegisterType((*StoreUpdateUserInfoResponse)(nil), "candy.meta.StoreUpdateUserInfoResponse")
	proto.RegisterType((*StoreUpdateUserPasswordRequest)(nil), "candy.meta.StoreUpdateUserPasswordRequest")
	proto.RegisterType((*StoreUpdateUserPasswordResponse)(nil), "candy.meta.StoreUpdateUserPasswordResponse")
	proto.RegisterType((*StoreGetUserInfoRequest)(nil), "candy.meta.StoreGetUserInfoRequest")
	proto.RegisterType((*StoreGetUserInfoResponse)(nil), "candy.meta.StoreGetUserInfoResponse")
	proto.RegisterType((*StoreAuthRequest)(nil), "candy.meta.StoreAuthRequest")
	proto.RegisterType((*StoreAuthResponse)(nil), "candy.meta.StoreAuthResponse")
	proto.RegisterType((*StoreCreateGroupRequest)(nil), "candy.meta.StoreCreateGroupRequest")
	proto.RegisterType((*StoreCreateGroupResponse)(nil), "candy.meta.StoreCreateGroupResponse")
	proto.RegisterType((*StoreNewMessageRequest)(nil), "candy.meta.StoreNewMessageRequest")
	proto.RegisterType((*StoreNewMessageResponse)(nil), "candy.meta.StoreNewMessageResponse")
	proto.RegisterType((*StoreUploadFileRequest)(nil), "candy.meta.StoreUploadFileRequest")
	proto.RegisterType((*StoreUploadFileResponse)(nil), "candy.meta.StoreUploadFileResponse")
	proto.RegisterType((*StoreCheckFileRequest)(nil), "candy.meta.StoreCheckFileRequest")
	proto.RegisterType((*StoreCheckFileResponse)(nil), "candy.meta.StoreCheckFileResponse")
	proto.RegisterType((*StoreDownloadFileRequest)(nil), "candy.meta.StoreDownloadFileRequest")
	proto.RegisterType((*StoreDownloadFileResponse)(nil), "candy.meta.StoreDownloadFileResponse")
	proto.RegisterType((*StoreSubscribeRequest)(nil), "candy.meta.StoreSubscribeRequest")
	proto.RegisterType((*StoreSubscribeResponse)(nil), "candy.meta.StoreSubscribeResponse")
	proto.RegisterType((*StoreUnSubscribeRequest)(nil), "candy.meta.StoreUnSubscribeRequest")
	proto.RegisterType((*StoreUnSubscribeResponse)(nil), "candy.meta.StoreUnSubscribeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Store service

type StoreClient interface {
	Register(ctx context.Context, in *StoreRegisterRequest, opts ...grpc.CallOption) (*StoreRegisterResponse, error)
	UpdateUserInfo(ctx context.Context, in *StoreUpdateUserInfoRequest, opts ...grpc.CallOption) (*StoreUpdateUserInfoResponse, error)
	UpdateUserPassword(ctx context.Context, in *StoreUpdateUserPasswordRequest, opts ...grpc.CallOption) (*StoreUpdateUserPasswordResponse, error)
	GetUserInfo(ctx context.Context, in *StoreGetUserInfoRequest, opts ...grpc.CallOption) (*StoreGetUserInfoResponse, error)
	Auth(ctx context.Context, in *StoreAuthRequest, opts ...grpc.CallOption) (*StoreAuthResponse, error)
	// AddFriend 添加好友
	AddFriend(ctx context.Context, in *StoreAddFriendRequest, opts ...grpc.CallOption) (*StoreAddFriendResponse, error)
	// FindUser 根据字符串的用户名模糊查用户列表
	FindUser(ctx context.Context, in *StoreFindUserRequest, opts ...grpc.CallOption) (*StoreFindUserResponse, error)
	CreateGroup(ctx context.Context, in *StoreCreateGroupRequest, opts ...grpc.CallOption) (*StoreCreateGroupResponse, error)
	NewMessage(ctx context.Context, in *StoreNewMessageRequest, opts ...grpc.CallOption) (*StoreNewMessageResponse, error)
	// UploadFile 上传文件接口，一次一个文件.
	UploadFile(ctx context.Context, in *StoreUploadFileRequest, opts ...grpc.CallOption) (*StoreUploadFileResponse, error)
	// CheckFile 检测文件是否存在，文件的MD5, 服务器返回不存在的文件MD5.
	CheckFile(ctx context.Context, in *StoreCheckFileRequest, opts ...grpc.CallOption) (*StoreCheckFileResponse, error)
	// DownloadFile 下载文件，传入文件MD5，返回具体文件内容.
	DownloadFile(ctx context.Context, in *StoreDownloadFileRequest, opts ...grpc.CallOption) (*StoreDownloadFileResponse, error)
	Subscribe(ctx context.Context, in *StoreSubscribeRequest, opts ...grpc.CallOption) (*StoreSubscribeResponse, error)
	UnSubscribe(ctx context.Context, in *StoreUnSubscribeRequest, opts ...grpc.CallOption) (*StoreUnSubscribeResponse, error)
}

type storeClient struct {
	cc *grpc.ClientConn
}

func NewStoreClient(cc *grpc.ClientConn) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) Register(ctx context.Context, in *StoreRegisterRequest, opts ...grpc.CallOption) (*StoreRegisterResponse, error) {
	out := new(StoreRegisterResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Store/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) UpdateUserInfo(ctx context.Context, in *StoreUpdateUserInfoRequest, opts ...grpc.CallOption) (*StoreUpdateUserInfoResponse, error) {
	out := new(StoreUpdateUserInfoResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Store/UpdateUserInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) UpdateUserPassword(ctx context.Context, in *StoreUpdateUserPasswordRequest, opts ...grpc.CallOption) (*StoreUpdateUserPasswordResponse, error) {
	out := new(StoreUpdateUserPasswordResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Store/UpdateUserPassword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) GetUserInfo(ctx context.Context, in *StoreGetUserInfoRequest, opts ...grpc.CallOption) (*StoreGetUserInfoResponse, error) {
	out := new(StoreGetUserInfoResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Store/GetUserInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) Auth(ctx context.Context, in *StoreAuthRequest, opts ...grpc.CallOption) (*StoreAuthResponse, error) {
	out := new(StoreAuthResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Store/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) AddFriend(ctx context.Context, in *StoreAddFriendRequest, opts ...grpc.CallOption) (*StoreAddFriendResponse, error) {
	out := new(StoreAddFriendResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Store/AddFriend", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) FindUser(ctx context.Context, in *StoreFindUserRequest, opts ...grpc.CallOption) (*StoreFindUserResponse, error) {
	out := new(StoreFindUserResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Store/FindUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) CreateGroup(ctx context.Context, in *StoreCreateGroupRequest, opts ...grpc.CallOption) (*StoreCreateGroupResponse, error) {
	out := new(StoreCreateGroupResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Store/CreateGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) NewMessage(ctx context.Context, in *StoreNewMessageRequest, opts ...grpc.CallOption) (*StoreNewMessageResponse, error) {
	out := new(StoreNewMessageResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Store/NewMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) UploadFile(ctx context.Context, in *StoreUploadFileRequest, opts ...grpc.CallOption) (*StoreUploadFileResponse, error) {
	out := new(StoreUploadFileResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Store/UploadFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) CheckFile(ctx context.Context, in *StoreCheckFileRequest, opts ...grpc.CallOption) (*StoreCheckFileResponse, error) {
	out := new(StoreCheckFileResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Store/CheckFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) DownloadFile(ctx context.Context, in *StoreDownloadFileRequest, opts ...grpc.CallOption) (*StoreDownloadFileResponse, error) {
	out := new(StoreDownloadFileResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Store/DownloadFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) Subscribe(ctx context.Context, in *StoreSubscribeRequest, opts ...grpc.CallOption) (*StoreSubscribeResponse, error) {
	out := new(StoreSubscribeResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Store/Subscribe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) UnSubscribe(ctx context.Context, in *StoreUnSubscribeRequest, opts ...grpc.CallOption) (*StoreUnSubscribeResponse, error) {
	out := new(StoreUnSubscribeResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Store/UnSubscribe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Store service

type StoreServer interface {
	Register(context.Context, *StoreRegisterRequest) (*StoreRegisterResponse, error)
	UpdateUserInfo(context.Context, *StoreUpdateUserInfoRequest) (*StoreUpdateUserInfoResponse, error)
	UpdateUserPassword(context.Context, *StoreUpdateUserPasswordRequest) (*StoreUpdateUserPasswordResponse, error)
	GetUserInfo(context.Context, *StoreGetUserInfoRequest) (*StoreGetUserInfoResponse, error)
	Auth(context.Context, *StoreAuthRequest) (*StoreAuthResponse, error)
	// AddFriend 添加好友
	AddFriend(context.Context, *StoreAddFriendRequest) (*StoreAddFriendResponse, error)
	// FindUser 根据字符串的用户名模糊查用户列表
	FindUser(context.Context, *StoreFindUserRequest) (*StoreFindUserResponse, error)
	CreateGroup(context.Context, *StoreCreateGroupRequest) (*StoreCreateGroupResponse, error)
	NewMessage(context.Context, *StoreNewMessageRequest) (*StoreNewMessageResponse, error)
	// UploadFile 上传文件接口，一次一个文件.
	UploadFile(context.Context, *StoreUploadFileRequest) (*StoreUploadFileResponse, error)
	// CheckFile 检测文件是否存在，文件的MD5, 服务器返回不存在的文件MD5.
	CheckFile(context.Context, *StoreCheckFileRequest) (*StoreCheckFileResponse, error)
	// DownloadFile 下载文件，传入文件MD5，返回具体文件内容.
	DownloadFile(context.Context, *StoreDownloadFileRequest) (*StoreDownloadFileResponse, error)
	Subscribe(context.Context, *StoreSubscribeRequest) (*StoreSubscribeResponse, error)
	UnSubscribe(context.Context, *StoreUnSubscribeRequest) (*StoreUnSubscribeResponse, error)
}

func RegisterStoreServer(s *grpc.Server, srv StoreServer) {
	s.RegisterService(&_Store_serviceDesc, srv)
}

func _Store_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Store/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Register(ctx, req.(*StoreRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_UpdateUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreUpdateUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).UpdateUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Store/UpdateUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).UpdateUserInfo(ctx, req.(*StoreUpdateUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_UpdateUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreUpdateUserPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).UpdateUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Store/UpdateUserPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).UpdateUserPassword(ctx, req.(*StoreUpdateUserPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreGetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Store/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetUserInfo(ctx, req.(*StoreGetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Store/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Auth(ctx, req.(*StoreAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_AddFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreAddFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).AddFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Store/AddFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).AddFriend(ctx, req.(*StoreAddFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_FindUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreFindUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).FindUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Store/FindUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).FindUser(ctx, req.(*StoreFindUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreCreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Store/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).CreateGroup(ctx, req.(*StoreCreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_NewMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreNewMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).NewMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Store/NewMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).NewMessage(ctx, req.(*StoreNewMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreUploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Store/UploadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).UploadFile(ctx, req.(*StoreUploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_CheckFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreCheckFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).CheckFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Store/CheckFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).CheckFile(ctx, req.(*StoreCheckFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_DownloadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreDownloadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).DownloadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Store/DownloadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).DownloadFile(ctx, req.(*StoreDownloadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreSubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Store/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Subscribe(ctx, req.(*StoreSubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_UnSubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreUnSubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).UnSubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Store/UnSubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).UnSubscribe(ctx, req.(*StoreUnSubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Store_serviceDesc = grpc.ServiceDesc{
	ServiceName: "candy.meta.Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Store_Register_Handler,
		},
		{
			MethodName: "UpdateUserInfo",
			Handler:    _Store_UpdateUserInfo_Handler,
		},
		{
			MethodName: "UpdateUserPassword",
			Handler:    _Store_UpdateUserPassword_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _Store_GetUserInfo_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _Store_Auth_Handler,
		},
		{
			MethodName: "AddFriend",
			Handler:    _Store_AddFriend_Handler,
		},
		{
			MethodName: "FindUser",
			Handler:    _Store_FindUser_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _Store_CreateGroup_Handler,
		},
		{
			MethodName: "NewMessage",
			Handler:    _Store_NewMessage_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _Store_UploadFile_Handler,
		},
		{
			MethodName: "CheckFile",
			Handler:    _Store_CheckFile_Handler,
		},
		{
			MethodName: "DownloadFile",
			Handler:    _Store_DownloadFile_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _Store_Subscribe_Handler,
		},
		{
			MethodName: "UnSubscribe",
			Handler:    _Store_UnSubscribe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor4,
}

func init() { proto.RegisterFile("store.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 861 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x57, 0x5b, 0x53, 0x1a, 0x4b,
	0x10, 0x2e, 0xae, 0x47, 0x1a, 0xe4, 0x78, 0xe6, 0xe4, 0x82, 0x9b, 0x1b, 0x59, 0x4d, 0xbc, 0x24,
	0x45, 0x25, 0xf8, 0x92, 0xf2, 0x25, 0x51, 0x14, 0x63, 0x25, 0x6a, 0x02, 0x52, 0x65, 0x2e, 0x2f,
	0x2b, 0x3b, 0x91, 0x2d, 0x61, 0x87, 0xec, 0x0c, 0x5a, 0xbe, 0xe6, 0x47, 0xe5, 0x9f, 0xe4, 0xff,
	0xa4, 0x76, 0x98, 0x5d, 0x86, 0x9d, 0x01, 0x75, 0x79, 0xd3, 0xda, 0xee, 0xaf, 0xbf, 0xf9, 0xba,
	0xa7, 0xbf, 0x01, 0xf2, 0x94, 0x11, 0x0f, 0x57, 0xfa, 0x1e, 0x61, 0x04, 0x41, 0xdb, 0x72, 0xed,
	0xab, 0x4a, 0x0f, 0x33, 0xcb, 0x28, 0xb4, 0x49, 0xaf, 0x47, 0xdc, 0xe1, 0x17, 0x73, 0x19, 0xee,
	0x34, 0xfd, 0xc0, 0xba, 0xe3, 0xda, 0x2d, 0x8a, 0xbd, 0x06, 0xfe, 0x39, 0xc0, 0x94, 0xa1, 0x02,
	0xa4, 0x07, 0x14, 0x7b, 0xa5, 0x44, 0x39, 0xb1, 0x9a, 0x33, 0x1b, 0x70, 0x37, 0x12, 0x45, 0xfb,
	0xc4, 0xa5, 0x18, 0xad, 0x43, 0xb6, 0x83, 0x2d, 0x5b, 0x04, 0xe6, 0xab, 0x46, 0x65, 0x54, 0xa9,
	0x12, 0x44, 0xbd, 0xe7, 0x11, 0x68, 0x1e, 0x32, 0x3e, 0x24, 0x2d, 0x25, 0xcb, 0xa9, 0xd5, 0x9c,
	0xf9, 0x5d, 0x60, 0x6e, 0xd9, 0x76, 0xdd, 0x73, 0xb0, 0x6b, 0x4b, 0xa5, 0xeb, 0x1e, 0xe9, 0x71,
	0xc4, 0x14, 0x02, 0x48, 0x1e, 0x93, 0x52, 0x92, 0xff, 0xbd, 0x06, 0x99, 0x26, 0xb3, 0x18, 0x2e,
	0xa5, 0xca, 0x89, 0xd5, 0xe2, 0x78, 0xb1, 0x00, 0xa3, 0x6b, 0x31, 0x87, 0xb8, 0x26, 0x81, 0x7b,
	0x51, 0xf4, 0x18, 0x94, 0xc3, 0x82, 0xc9, 0x6b, 0x0b, 0x6e, 0x0b, 0x21, 0x1b, 0xf8, 0xcc, 0xa1,
	0x6c, 0x24, 0x24, 0x40, 0x72, 0x7f, 0x47, 0x9c, 0xa5, 0x00, 0x69, 0x5f, 0x3d, 0x8e, 0x96, 0x43,
	0x0b, 0x30, 0xf7, 0xc9, 0xa2, 0xf4, 0x92, 0x78, 0x36, 0x3f, 0x50, 0xce, 0xac, 0x09, 0x49, 0x46,
	0x18, 0xb7, 0xe7, 0x6c, 0x7e, 0x04, 0x83, 0x83, 0xb4, 0xfa, 0xb6, 0xc5, 0xb0, 0x5f, 0x6f, 0xdf,
	0xfd, 0x41, 0x24, 0x71, 0x5b, 0x61, 0x5f, 0x7d, 0x0a, 0x87, 0x4e, 0xfb, 0xfc, 0xd0, 0xea, 0x61,
	0x41, 0xaa, 0x08, 0xd9, 0xad, 0x0b, 0x8b, 0x59, 0x1e, 0xa7, 0x54, 0x30, 0x5b, 0xf0, 0x40, 0x8b,
	0x16, 0x43, 0xcc, 0xa1, 0x12, 0xbc, 0x93, 0xe6, 0x3b, 0x78, 0x1c, 0x81, 0x0d, 0xa4, 0x98, 0x48,
	0x34, 0xd4, 0x8a, 0x13, 0x35, 0xbf, 0xc0, 0x93, 0x89, 0x08, 0x33, 0x92, 0x5b, 0x81, 0xfb, 0x1c,
	0x7a, 0x0f, 0xb3, 0xa9, 0xf2, 0x99, 0xbf, 0x12, 0x50, 0x52, 0x23, 0x67, 0xab, 0x1e, 0x96, 0x48,
	0x29, 0x1d, 0x4a, 0x47, 0x3a, 0x94, 0xe1, 0x1d, 0xaa, 0xc2, 0xc2, 0x70, 0xd2, 0x07, 0xac, 0x73,
	0x53, 0xf1, 0x3e, 0xc0, 0x7f, 0x52, 0xce, 0x8c, 0x72, 0x6d, 0x0a, 0xb9, 0x6a, 0x1e, 0xb6, 0x18,
	0xde, 0xf3, 0xc8, 0xa0, 0x1f, 0xf0, 0x28, 0x42, 0x96, 0xeb, 0x12, 0x5c, 0x80, 0x7f, 0xe1, 0x1f,
	0xfe, 0x3d, 0xcc, 0xad, 0x0b, 0x01, 0xc7, 0x72, 0x63, 0x0c, 0xfd, 0xa6, 0xb8, 0xee, 0x87, 0xf8,
	0xf2, 0x00, 0x53, 0x6a, 0x9d, 0xe1, 0x80, 0x42, 0x19, 0x52, 0x07, 0xf4, 0x4c, 0x40, 0xfc, 0x2f,
	0x43, 0x88, 0x40, 0x73, 0x57, 0xf0, 0x97, 0x73, 0x63, 0x50, 0xf8, 0x2c, 0x28, 0xb4, 0xfa, 0x5d,
	0x62, 0xd9, 0x75, 0xa7, 0x1b, 0x52, 0x58, 0x8b, 0xa0, 0x2c, 0x8e, 0xa3, 0xf0, 0x20, 0xa1, 0xab,
	0xbf, 0xfb, 0x9c, 0xee, 0xf0, 0x32, 0x16, 0x42, 0x66, 0x32, 0x64, 0x2c, 0x66, 0xc3, 0xb5, 0x52,
	0xeb, 0xe0, 0xf6, 0x79, 0x4c, 0x62, 0xf3, 0x90, 0xf1, 0x67, 0x30, 0x58, 0xde, 0x4d, 0x71, 0x58,
	0x09, 0x32, 0x9e, 0x23, 0xc8, 0xa0, 0xc7, 0x62, 0x18, 0x76, 0xc8, 0xa5, 0x3b, 0x83, 0x86, 0x11,
	0xd4, 0xdf, 0x09, 0x58, 0xd4, 0xc0, 0xc6, 0xa0, 0xfb, 0x16, 0x32, 0x7e, 0xee, 0x10, 0x38, 0x5f,
	0x7d, 0x25, 0x87, 0x4e, 0xac, 0x50, 0xe1, 0x29, 0xbb, 0x2e, 0xf3, 0xae, 0x8c, 0x97, 0x00, 0xa3,
	0xff, 0x50, 0x1e, 0x52, 0xe7, 0xf8, 0x4a, 0xdc, 0xd1, 0x79, 0xc8, 0x5c, 0x58, 0xdd, 0x81, 0xe8,
	0xfc, 0x66, 0xf2, 0x4d, 0xc2, 0x7c, 0x2d, 0xda, 0xd6, 0x1c, 0x9c, 0xd2, 0xb6, 0xe7, 0x9c, 0xe2,
	0x09, 0x96, 0xd2, 0x21, 0x94, 0x89, 0x7b, 0xbd, 0x23, 0xda, 0x22, 0xa5, 0xc4, 0x98, 0x97, 0x8d,
	0x60, 0xec, 0xdc, 0x5b, 0x94, 0x0e, 0x6e, 0xf2, 0x58, 0xd2, 0xed, 0x8b, 0x57, 0xff, 0xe4, 0x7c,
	0xcf, 0x25, 0x1e, 0x46, 0x47, 0x30, 0x17, 0x18, 0x21, 0x2a, 0x2b, 0x5a, 0x47, 0x7c, 0xd6, 0x78,
	0x3a, 0x25, 0x42, 0xd0, 0xb0, 0xa0, 0x38, 0x6e, 0x63, 0xe8, 0xb9, 0x92, 0xa4, 0x75, 0x4d, 0x63,
	0xe5, 0xda, 0x38, 0x51, 0xa2, 0x07, 0x48, 0x35, 0x24, 0xb4, 0x3e, 0x25, 0x3d, 0xe2, 0x7b, 0xc6,
	0x8b, 0x1b, 0xc5, 0x8a, 0x72, 0x27, 0x90, 0x97, 0xac, 0x07, 0x2d, 0x29, 0xb9, 0xaa, 0x85, 0x19,
	0xcb, 0xd3, 0x83, 0x04, 0x72, 0x0d, 0xd2, 0xbe, 0x39, 0xa0, 0x87, 0x4a, 0xb4, 0xe4, 0x33, 0xc6,
	0xa3, 0x09, 0x5f, 0x05, 0x48, 0x03, 0x72, 0xe1, 0xfb, 0x0b, 0xa9, 0x0d, 0x8a, 0xbe, 0xfc, 0x0c,
	0x73, 0x5a, 0x88, 0xc0, 0x3c, 0x82, 0xb9, 0xe0, 0x15, 0xaa, 0x99, 0x8a, 0xc8, 0x33, 0x56, 0x33,
	0x15, 0xca, 0x13, 0xf6, 0x04, 0xf2, 0x92, 0xfb, 0x68, 0x34, 0x54, 0x7d, 0x4d, 0xa3, 0xa1, 0xce,
	0xc0, 0x5a, 0x00, 0x23, 0x4f, 0x41, 0xea, 0xe1, 0x14, 0xb3, 0x32, 0x96, 0xa6, 0xc6, 0x8c, 0x60,
	0x47, 0x86, 0xa0, 0x81, 0x55, 0x0c, 0x48, 0x03, 0xab, 0x71, 0x94, 0x06, 0xe4, 0xc2, 0x6d, 0xae,
	0x69, 0x56, 0xd4, 0x3c, 0x34, 0xcd, 0x52, 0xcd, 0xe0, 0x1b, 0x14, 0xe4, 0x9d, 0x88, 0x96, 0xaf,
	0x59, 0x99, 0x43, 0xe4, 0x67, 0x37, 0x5a, 0xac, 0x3e, 0xe1, 0x70, 0xd5, 0x68, 0x08, 0x47, 0x77,
	0x97, 0x86, 0xb0, 0xba, 0xa9, 0x4e, 0x20, 0x2f, 0x2d, 0x30, 0xcd, 0x30, 0xa8, 0x3b, 0x51, 0x33,
	0x0c, 0x9a, 0x1d, 0xb8, 0x9d, 0xfd, 0x9a, 0xf6, 0x03, 0x4e, 0xb3, 0xfc, 0x77, 0xd7, 0xc6, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0xf7, 0x4f, 0xdc, 0xa0, 0x0d, 0x00, 0x00,
}
