// Code generated by protoc-gen-go.
// source: store.proto
// DO NOT EDIT!

package meta

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type FindUserRequest struct {
	User string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *FindUserRequest) Reset()                    { *m = FindUserRequest{} }
func (m *FindUserRequest) String() string            { return proto.CompactTextString(m) }
func (*FindUserRequest) ProtoMessage()               {}
func (*FindUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

type FindUserResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ID     int64           `protobuf:"varint,2,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *FindUserResponse) Reset()                    { *m = FindUserResponse{} }
func (m *FindUserResponse) String() string            { return proto.CompactTextString(m) }
func (*FindUserResponse) ProtoMessage()               {}
func (*FindUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *FindUserResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type AddFriendRequest struct {
	From    int64 `protobuf:"varint,1,opt,name=From,json=from" json:"From,omitempty"`
	To      int64 `protobuf:"varint,2,opt,name=To,json=to" json:"To,omitempty"`
	Confirm bool  `protobuf:"varint,3,opt,name=Confirm,json=confirm" json:"Confirm,omitempty"`
}

func (m *AddFriendRequest) Reset()                    { *m = AddFriendRequest{} }
func (m *AddFriendRequest) String() string            { return proto.CompactTextString(m) }
func (*AddFriendRequest) ProtoMessage()               {}
func (*AddFriendRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

type AddFriendResponse struct {
	Header  *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Confirm bool            `protobuf:"varint,2,opt,name=Confirm,json=confirm" json:"Confirm,omitempty"`
}

func (m *AddFriendResponse) Reset()                    { *m = AddFriendResponse{} }
func (m *AddFriendResponse) String() string            { return proto.CompactTextString(m) }
func (*AddFriendResponse) ProtoMessage()               {}
func (*AddFriendResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *AddFriendResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type RegisterRequest struct {
	ID       int64  `protobuf:"varint,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	User     string `protobuf:"bytes,2,opt,name=User,json=user" json:"User,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=Password,json=password" json:"Password,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

type RegisterResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

func (m *RegisterResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type AuthRequest struct {
	User     string `protobuf:"bytes,1,opt,name=User,json=user" json:"User,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,json=password" json:"Password,omitempty"`
}

func (m *AuthRequest) Reset()                    { *m = AuthRequest{} }
func (m *AuthRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()               {}
func (*AuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{6} }

type AuthResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ID     int64           `protobuf:"varint,2,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *AuthResponse) Reset()                    { *m = AuthResponse{} }
func (m *AuthResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()               {}
func (*AuthResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{7} }

func (m *AuthResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type CreateGroupRequest struct {
	UserID  int64 `protobuf:"varint,1,opt,name=UserID,json=userID" json:"UserID,omitempty"`
	GroupID int64 `protobuf:"varint,2,opt,name=GroupID,json=groupID" json:"GroupID,omitempty"`
}

func (m *CreateGroupRequest) Reset()                    { *m = CreateGroupRequest{} }
func (m *CreateGroupRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateGroupRequest) ProtoMessage()               {}
func (*CreateGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{8} }

type CreateGroupResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *CreateGroupResponse) Reset()                    { *m = CreateGroupResponse{} }
func (m *CreateGroupResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateGroupResponse) ProtoMessage()               {}
func (*CreateGroupResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{9} }

func (m *CreateGroupResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type NewMessageRequest struct {
	Msg *Message `protobuf:"bytes,1,opt,name=Msg,json=msg" json:"Msg,omitempty"`
}

func (m *NewMessageRequest) Reset()                    { *m = NewMessageRequest{} }
func (m *NewMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*NewMessageRequest) ProtoMessage()               {}
func (*NewMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{10} }

func (m *NewMessageRequest) GetMsg() *Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

type NewMessageResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *NewMessageResponse) Reset()                    { *m = NewMessageResponse{} }
func (m *NewMessageResponse) String() string            { return proto.CompactTextString(m) }
func (*NewMessageResponse) ProtoMessage()               {}
func (*NewMessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{11} }

func (m *NewMessageResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*FindUserRequest)(nil), "candy.meta.FindUserRequest")
	proto.RegisterType((*FindUserResponse)(nil), "candy.meta.FindUserResponse")
	proto.RegisterType((*AddFriendRequest)(nil), "candy.meta.AddFriendRequest")
	proto.RegisterType((*AddFriendResponse)(nil), "candy.meta.AddFriendResponse")
	proto.RegisterType((*RegisterRequest)(nil), "candy.meta.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "candy.meta.RegisterResponse")
	proto.RegisterType((*AuthRequest)(nil), "candy.meta.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "candy.meta.AuthResponse")
	proto.RegisterType((*CreateGroupRequest)(nil), "candy.meta.CreateGroupRequest")
	proto.RegisterType((*CreateGroupResponse)(nil), "candy.meta.CreateGroupResponse")
	proto.RegisterType((*NewMessageRequest)(nil), "candy.meta.NewMessageRequest")
	proto.RegisterType((*NewMessageResponse)(nil), "candy.meta.NewMessageResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Store service

type StoreClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// AddFriend 添加好友，两人都添加过对方后才可以聊天.
	AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error)
	// FindUser 根据字符串的用户名查的用户信息.
	FindUser(ctx context.Context, in *FindUserRequest, opts ...grpc.CallOption) (*FindUserResponse, error)
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error)
	NewMessage(ctx context.Context, in *NewMessageRequest, opts ...grpc.CallOption) (*NewMessageResponse, error)
}

type storeClient struct {
	cc *grpc.ClientConn
}

func NewStoreClient(cc *grpc.ClientConn) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Store/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Store/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error) {
	out := new(AddFriendResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Store/AddFriend", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) FindUser(ctx context.Context, in *FindUserRequest, opts ...grpc.CallOption) (*FindUserResponse, error) {
	out := new(FindUserResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Store/FindUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error) {
	out := new(CreateGroupResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Store/CreateGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) NewMessage(ctx context.Context, in *NewMessageRequest, opts ...grpc.CallOption) (*NewMessageResponse, error) {
	out := new(NewMessageResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Store/NewMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Store service

type StoreServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
	// AddFriend 添加好友，两人都添加过对方后才可以聊天.
	AddFriend(context.Context, *AddFriendRequest) (*AddFriendResponse, error)
	// FindUser 根据字符串的用户名查的用户信息.
	FindUser(context.Context, *FindUserRequest) (*FindUserResponse, error)
	CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error)
	NewMessage(context.Context, *NewMessageRequest) (*NewMessageResponse, error)
}

func RegisterStoreServer(s *grpc.Server, srv StoreServer) {
	s.RegisterService(&_Store_serviceDesc, srv)
}

func _Store_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Store/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Store/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_AddFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).AddFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Store/AddFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).AddFriend(ctx, req.(*AddFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_FindUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).FindUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Store/FindUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).FindUser(ctx, req.(*FindUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Store/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_NewMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).NewMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Store/NewMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).NewMessage(ctx, req.(*NewMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Store_serviceDesc = grpc.ServiceDesc{
	ServiceName: "candy.meta.Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Store_Register_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _Store_Auth_Handler,
		},
		{
			MethodName: "AddFriend",
			Handler:    _Store_AddFriend_Handler,
		},
		{
			MethodName: "FindUser",
			Handler:    _Store_FindUser_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _Store_CreateGroup_Handler,
		},
		{
			MethodName: "NewMessage",
			Handler:    _Store_NewMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor4,
}

func init() { proto.RegisterFile("store.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0x56, 0x92, 0x92, 0xa6, 0xaf, 0x13, 0xeb, 0x3c, 0x09, 0xa2, 0x00, 0xa3, 0x8a, 0x34, 0xa9,
	0xa7, 0x1e, 0xca, 0x09, 0x24, 0x0e, 0x63, 0x5b, 0xe8, 0x84, 0x36, 0x0d, 0xc3, 0x38, 0x70, 0x0b,
	0x8d, 0x97, 0xe5, 0x90, 0xb8, 0xd8, 0x89, 0x26, 0xfe, 0x32, 0xfe, 0x3d, 0x64, 0xc7, 0x6e, 0xec,
	0x86, 0x5e, 0xb6, 0xdd, 0xfc, 0xf4, 0xbe, 0xf7, 0xbd, 0xef, 0xfd, 0xf0, 0x83, 0x31, 0xaf, 0x29,
	0x23, 0xf3, 0x35, 0xa3, 0x35, 0x45, 0xb0, 0x4a, 0xab, 0xec, 0xcf, 0xbc, 0x24, 0x75, 0x1a, 0xed,
	0xad, 0x68, 0x59, 0xd2, 0xaa, 0xf5, 0xc4, 0xc7, 0xb0, 0x9f, 0x14, 0x55, 0x76, 0xc3, 0x09, 0xc3,
	0xe4, 0x77, 0x43, 0x78, 0x8d, 0x10, 0x0c, 0x1a, 0x4e, 0x58, 0xe8, 0x4c, 0x9d, 0xd9, 0x08, 0xcb,
	0x77, 0xfc, 0x03, 0x26, 0x1d, 0x8c, 0xaf, 0x69, 0xc5, 0x09, 0x5a, 0x80, 0x7f, 0x47, 0xd2, 0x4c,
	0x21, 0xc7, 0x8b, 0x68, 0xde, 0x65, 0x99, 0x6b, 0xd4, 0x52, 0x22, 0xb0, 0x42, 0xa2, 0xe7, 0xe0,
	0x5e, 0x9c, 0x85, 0xee, 0xd4, 0x99, 0x79, 0xd8, 0x2d, 0xce, 0xe2, 0x6b, 0x98, 0x9c, 0x64, 0x59,
	0xc2, 0x0a, 0x52, 0x65, 0x46, 0xfe, 0x84, 0xd1, 0x52, 0xb2, 0x7a, 0x78, 0x70, 0xcb, 0x68, 0x29,
	0xe2, 0xbe, 0x53, 0x1d, 0x57, 0x53, 0x14, 0xc2, 0xf0, 0x94, 0x56, 0xb7, 0x05, 0x2b, 0x43, 0x6f,
	0xea, 0xcc, 0x02, 0x3c, 0x5c, 0xb5, 0x66, 0x9c, 0xc2, 0x81, 0xc1, 0xf8, 0x08, 0xa9, 0x46, 0x0a,
	0xd7, 0x4e, 0xf1, 0x15, 0xf6, 0x31, 0xc9, 0x0b, 0x5e, 0x77, 0x3d, 0x6b, 0xeb, 0x72, 0x74, 0x5d,
	0xa2, 0x06, 0xd1, 0x2b, 0x19, 0xa9, 0x7a, 0x88, 0x22, 0x08, 0xae, 0x53, 0xce, 0xef, 0x29, 0xcb,
	0xa4, 0xe8, 0x11, 0x0e, 0xd6, 0xca, 0x8e, 0x13, 0x98, 0x74, 0x94, 0x0f, 0x17, 0x1d, 0x7f, 0x84,
	0xf1, 0x49, 0x53, 0xdf, 0x19, 0xad, 0xbc, 0xd9, 0x1a, 0xa5, 0x25, 0xc3, 0xdd, 0x92, 0x81, 0x61,
	0xaf, 0x0d, 0x7f, 0xc2, 0x11, 0x27, 0x80, 0x4e, 0x19, 0x49, 0x6b, 0xf2, 0x99, 0xd1, 0x66, 0xad,
	0x95, 0xbd, 0x00, 0x5f, 0x28, 0xdb, 0x34, 0xcd, 0x6f, 0xa4, 0x25, 0xba, 0x2e, 0x71, 0x1b, 0x8a,
	0x61, 0xde, 0x9a, 0xf1, 0x05, 0x1c, 0x5a, 0x3c, 0x8f, 0xe8, 0xd2, 0x07, 0x38, 0xb8, 0x22, 0xf7,
	0x97, 0x84, 0xf3, 0x34, 0x27, 0x5a, 0xd1, 0x31, 0x78, 0x97, 0x3c, 0x57, 0x2c, 0x87, 0x26, 0x8b,
	0x06, 0x7a, 0x25, 0xcf, 0xe3, 0x25, 0x20, 0x33, 0xf6, 0xe1, 0x2a, 0x16, 0x7f, 0x3d, 0x78, 0xf6,
	0x4d, 0x7c, 0x52, 0x74, 0x0e, 0x81, 0x9e, 0x3e, 0x7a, 0x65, 0x47, 0x5a, 0x6b, 0x16, 0xbd, 0xfe,
	0xbf, 0x53, 0x89, 0x78, 0x0f, 0x03, 0x31, 0x3d, 0xf4, 0xd2, 0x44, 0x19, 0xeb, 0x10, 0x85, 0x7d,
	0x87, 0x0a, 0x5d, 0xc2, 0x68, 0xf3, 0x6b, 0x90, 0x95, 0x65, 0xfb, 0x7b, 0x46, 0x6f, 0x76, 0x78,
	0x15, 0xd3, 0x39, 0x04, 0xfa, 0x52, 0xd8, 0xb5, 0x6c, 0x9d, 0x19, 0xbb, 0x96, 0xde, 0x71, 0xb9,
	0x82, 0xb1, 0x31, 0x6d, 0x74, 0x64, 0x82, 0xfb, 0xeb, 0x14, 0xbd, 0xdd, 0xe9, 0x57, 0x7c, 0x5f,
	0x00, 0xba, 0xb1, 0x21, 0xab, 0x86, 0xde, 0x2a, 0x44, 0x47, 0xbb, 0xdc, 0x2d, 0xd9, 0x27, 0xff,
	0xe7, 0x40, 0xb8, 0x7e, 0xf9, 0xf2, 0x86, 0xbe, 0xfb, 0x17, 0x00, 0x00, 0xff, 0xff, 0x18, 0xe9,
	0xf7, 0x7a, 0x6c, 0x05, 0x00, 0x00,
}
