// Code generated by protoc-gen-go.
// source: common.proto
// DO NOT EDIT!

/*
Package meta is a generated protocol buffer package.

It is generated from these files:
	common.proto
	gate.proto
	master.proto
	notice.proto
	store.proto

It has these top-level messages:
	RequestHeader
	ResponseHeader
	PushID
	Message
	GroupInfo
	PushMessage
	GateFindUserRequest
	GateFindUserResponse
	GateFriendRequest
	GateFriendResponse
	GateCreateGroupRequest
	GateCreateGroupResponse
	GateRegisterRequest
	GateRegisterResponse
	GateUpdateUserInfoRequest
	GateUpdateUserInfoResponse
	GateUpdateUserPasswordRequest
	GateUpdateUserPasswordResponse
	GateGetUserInfoRequest
	GateGetUserInfoResponse
	GateHeartbeatRequest
	GateHeartbeatResponse
	GateUserLoginRequest
	GateUserLoginResponse
	GateUserLogoutRequest
	GateUserLogoutResponse
	GateUploadFileRequest
	GateUploadFileResponse
	GateCheckFileRequest
	GateCheckFileResponse
	GateDownloadFileRequest
	GateDownloadFileResponse
	GatePushRequest
	GatePushResponse
	GateLoadMessageRequest
	GateLoadMessageResponse
	GateLoadGroupListRequest
	GateLoadGroupListResponse
	GateLoadFriendListRequest
	GateLoadFriendListResponse
	GateSendMessageRequest
	GateSendMessageResponse
	GateGroupRequest
	GateGroupResponse
	GateGroupCreateRequest
	GateGroupCreateResponse
	GateGroupDeleteRequest
	GateGroupDeleteResponse
	NewIDRequest
	NewIDResponse
	SubscribeRequest
	SubscribeResponse
	UnSubscribeRequest
	UnSubscribeResponse
	PushRequest
	PushResponse
	StoreFindUserRequest
	StoreFindUserResponse
	StoreFriendRequest
	StoreFriendResponse
	StoreRegisterRequest
	StoreRegisterResponse
	StoreUpdateUserInfoRequest
	StoreUpdateUserInfoResponse
	StoreUpdateUserPasswordRequest
	StoreUpdateUserPasswordResponse
	StoreGetUserInfoRequest
	StoreGetUserInfoResponse
	StoreAuthRequest
	StoreAuthResponse
	StoreGroupCreateRequest
	StoreGroupCreateResponse
	StoreGroupRequest
	StoreGroupResponse
	StoreGroupDeleteRequest
	StoreGroupDeleteResponse
	StoreNewMessageRequest
	StoreNewMessageResponse
	StoreUploadFileRequest
	StoreUploadFileResponse
	StoreCheckFileRequest
	StoreCheckFileResponse
	StoreDownloadFileRequest
	StoreDownloadFileResponse
	StoreLoadMessageRequest
	StoreLoadMessageResponse
	StoreLoadGroupListRequest
	StoreLoadGroupListResponse
	StoreLoadFriendListRequest
	StoreLoadFriendListResponse
*/
package meta

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Relation int32

const (
	//  没关系, 已删除
	Relation_Del Relation = 0
	// 添加
	Relation_Add Relation = 1
	// 确认
	Relation_Confirm Relation = 2
	// 拒绝
	Relation_Refuse Relation = 4
)

var Relation_name = map[int32]string{
	0: "Del",
	1: "Add",
	2: "Confirm",
	4: "Refuse",
}
var Relation_value = map[string]int32{
	"Del":     0,
	"Add":     1,
	"Confirm": 2,
	"Refuse":  4,
}

func (x Relation) String() string {
	return proto.EnumName(Relation_name, int32(x))
}
func (Relation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Event 事件（消息类型）
type Event int32

const (
	// 普通聊天的消息下推
	Event_None Event = 0
	// 群消息
	Event_Group Event = 1
	// 好友关系
	Event_Friend Event = 2
	// 上线
	Event_Online Event = 3
	// 下线
	Event_Offline Event = 4
	// 通知
	Event_Notice Event = 5
)

var Event_name = map[int32]string{
	0: "None",
	1: "Group",
	2: "Friend",
	3: "Online",
	4: "Offline",
	5: "Notice",
}
var Event_value = map[string]int32{
	"None":    0,
	"Group":   1,
	"Friend":  2,
	"Online":  3,
	"Offline": 4,
	"Notice":  5,
}

func (x Event) String() string {
	return proto.EnumName(Event_name, int32(x))
}
func (Event) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// RequestHeader Gate向后端发请求时，带上这个头，方便记录具体操作信息.
type RequestHeader struct {
	User int64 `protobuf:"varint,1,opt,name=User,json=user" json:"User,omitempty"`
}

func (m *RequestHeader) Reset()                    { *m = RequestHeader{} }
func (m *RequestHeader) String() string            { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()               {}
func (*RequestHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ResponseHeader struct {
	Code int32  `protobuf:"varint,1,opt,name=Code,json=code" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg,json=msg" json:"Msg,omitempty"`
}

func (m *ResponseHeader) Reset()                    { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string            { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()               {}
func (*ResponseHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// PushID 用户的上一条消息ID,用户ID
type PushID struct {
	User   int64 `protobuf:"varint,1,opt,name=User,json=user" json:"User,omitempty"`
	Before int64 `protobuf:"varint,2,opt,name=Before,json=before" json:"Before,omitempty"`
}

func (m *PushID) Reset()                    { *m = PushID{} }
func (m *PushID) String() string            { return proto.CompactTextString(m) }
func (*PushID) ProtoMessage()               {}
func (*PushID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Message struct {
	// ID 客户端发送过来时这个字段为0， gate收到后写入实际从master处获取到的消息ID
	ID int64 `protobuf:"varint,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	// Before 前一第消息的ID，用来确定是否有消息丢失
	Before int64 `protobuf:"varint,2,opt,name=Before,json=before" json:"Before,omitempty"`
	// Group 如果当前为群聊，设置为群组ID, 否则为0
	Group int64 `protobuf:"varint,3,opt,name=Group,json=group" json:"Group,omitempty"`
	// From 发消息的人的ID
	From int64 `protobuf:"varint,4,opt,name=From,json=from" json:"From,omitempty"`
	// To 如果当前为私聊，这个设置为收消息用户的ID, 否则为0
	To   int64  `protobuf:"varint,5,opt,name=To,json=to" json:"To,omitempty"`
	Body string `protobuf:"bytes,6,opt,name=Body,json=body" json:"Body,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// GroupInfo 群信息，目前只有名字，公告，头像
type GroupInfo struct {
	Active bool   `protobuf:"varint,1,opt,name=Active,json=active" json:"Active,omitempty"`
	ID     int64  `protobuf:"varint,2,opt,name=ID,json=iD" json:"ID,omitempty"`
	Owner  int64  `protobuf:"varint,3,opt,name=Owner,json=owner" json:"Owner,omitempty"`
	Name   string `protobuf:"bytes,4,opt,name=Name,json=name" json:"Name,omitempty"`
	Avatar string `protobuf:"bytes,5,opt,name=Avatar,json=avatar" json:"Avatar,omitempty"`
	Notice string `protobuf:"bytes,6,opt,name=Notice,json=notice" json:"Notice,omitempty"`
	// Admins 管理员
	Admins []int64 `protobuf:"varint,7,rep,packed,name=Admins,json=admins" json:"Admins,omitempty"`
	// Member 成员
	Member []int64 `protobuf:"varint,8,rep,packed,name=Member,json=member" json:"Member,omitempty"`
}

func (m *GroupInfo) Reset()                    { *m = GroupInfo{} }
func (m *GroupInfo) String() string            { return proto.CompactTextString(m) }
func (*GroupInfo) ProtoMessage()               {}
func (*GroupInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// 下推的消息，有系统消息(加群，加好友，上线通知啥的)，正常聊天消息
type PushMessage struct {
	// 消息类型，如好友，群，通知， 上线，下线之类的操作
	Event Event `protobuf:"varint,1,opt,name=Event,json=event,enum=candy.meta.Event" json:"Event,omitempty"`
	// 关系操作，加好友，删除好友，T出群，加入群
	Operate Relation `protobuf:"varint,2,opt,name=Operate,json=operate,enum=candy.meta.Relation" json:"Operate,omitempty"`
	// 具体消息
	Msg *Message `protobuf:"bytes,3,opt,name=Msg,json=msg" json:"Msg,omitempty"`
}

func (m *PushMessage) Reset()                    { *m = PushMessage{} }
func (m *PushMessage) String() string            { return proto.CompactTextString(m) }
func (*PushMessage) ProtoMessage()               {}
func (*PushMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PushMessage) GetMsg() *Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*RequestHeader)(nil), "candy.meta.RequestHeader")
	proto.RegisterType((*ResponseHeader)(nil), "candy.meta.ResponseHeader")
	proto.RegisterType((*PushID)(nil), "candy.meta.PushID")
	proto.RegisterType((*Message)(nil), "candy.meta.Message")
	proto.RegisterType((*GroupInfo)(nil), "candy.meta.GroupInfo")
	proto.RegisterType((*PushMessage)(nil), "candy.meta.PushMessage")
	proto.RegisterEnum("candy.meta.Relation", Relation_name, Relation_value)
	proto.RegisterEnum("candy.meta.Event", Event_name, Event_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x53, 0x4f, 0x8f, 0xd3, 0x3e,
	0x10, 0xdd, 0x34, 0xff, 0xda, 0xe9, 0xef, 0x57, 0x05, 0x53, 0xa1, 0x1c, 0xab, 0x20, 0xc4, 0x6a,
	0x0f, 0x3d, 0x94, 0x3f, 0xf7, 0xed, 0x96, 0x85, 0x1e, 0xda, 0x22, 0x0b, 0x2e, 0xdc, 0xdc, 0x66,
	0x52, 0x22, 0xd5, 0x9e, 0x62, 0x3b, 0x45, 0x3d, 0xf1, 0x09, 0xf8, 0x48, 0x7c, 0x37, 0x64, 0x27,
	0x65, 0xf7, 0x00, 0xa7, 0xe4, 0x8d, 0xdf, 0x7b, 0xf3, 0x66, 0x9c, 0xc0, 0x7f, 0x3b, 0x92, 0x92,
	0xd4, 0xf4, 0xa8, 0xc9, 0x12, 0x83, 0x9d, 0x50, 0xe5, 0x79, 0x2a, 0xd1, 0x8a, 0xe2, 0x39, 0xfc,
	0xcf, 0xf1, 0x5b, 0x83, 0xc6, 0x7e, 0x40, 0x51, 0xa2, 0x66, 0x0c, 0xa2, 0xcf, 0x06, 0x75, 0x1e,
	0x4c, 0x82, 0xeb, 0x90, 0x47, 0x8d, 0x41, 0x5d, 0xbc, 0x85, 0x11, 0x47, 0x73, 0x24, 0x65, 0xf0,
	0x81, 0x75, 0x47, 0x25, 0x7a, 0x56, 0xcc, 0xa3, 0x1d, 0x95, 0xc8, 0x32, 0x08, 0x57, 0x66, 0x9f,
	0xf7, 0x26, 0xc1, 0xf5, 0x80, 0x87, 0xd2, 0xec, 0x8b, 0xd7, 0x90, 0x7c, 0x6c, 0xcc, 0xd7, 0xe5,
	0xe2, 0x6f, 0xae, 0xec, 0x19, 0x24, 0x73, 0xac, 0x48, 0xa3, 0x97, 0x84, 0x3c, 0xd9, 0x7a, 0x54,
	0xfc, 0x80, 0x74, 0x85, 0xc6, 0x88, 0x3d, 0xb2, 0x11, 0xf4, 0x96, 0x8b, 0x4e, 0xd4, 0xab, 0x17,
	0xff, 0x92, 0xb0, 0x31, 0xc4, 0xef, 0x35, 0x35, 0xc7, 0x3c, 0xf4, 0xe5, 0x78, 0xef, 0x80, 0x6b,
	0x7a, 0xaf, 0x49, 0xe6, 0x51, 0xdb, 0xb4, 0xd2, 0x24, 0x9d, 0xe3, 0x27, 0xca, 0xe3, 0xd6, 0xd1,
	0x92, 0xe3, 0xcc, 0xa9, 0x3c, 0xe7, 0x89, 0x4f, 0x1d, 0x6d, 0xa9, 0x3c, 0x17, 0xbf, 0x02, 0x18,
	0x78, 0xbb, 0xa5, 0xaa, 0xc8, 0xf5, 0xbc, 0xdd, 0xd9, 0xfa, 0xd4, 0x0e, 0xdb, 0xe7, 0x89, 0xf0,
	0xa8, 0xcb, 0xd6, 0xfb, 0x93, 0x6d, 0x0c, 0xf1, 0xe6, 0xbb, 0x42, 0x7d, 0xc9, 0x40, 0x0e, 0x38,
	0xff, 0xb5, 0x90, 0xe8, 0x33, 0x0c, 0x78, 0xa4, 0x84, 0x44, 0xef, 0x78, 0x12, 0x56, 0x68, 0x9f,
	0x63, 0xc0, 0x13, 0xe1, 0x91, 0xab, 0xaf, 0xc9, 0xd6, 0x3b, 0xec, 0xd2, 0x24, 0xca, 0x23, 0xcf,
	0x2f, 0x65, 0xad, 0x4c, 0x9e, 0x4e, 0x42, 0x37, 0xb5, 0xf0, 0xc8, 0xd5, 0x57, 0x28, 0xb7, 0xa8,
	0xf3, 0x7e, 0x5b, 0x97, 0x1e, 0x15, 0x3f, 0x03, 0x18, 0xba, 0xbd, 0x5f, 0xb6, 0xf8, 0x12, 0xe2,
	0x77, 0x27, 0x54, 0xd6, 0x0f, 0x30, 0x9a, 0x3d, 0x99, 0x3e, 0xdc, 0xff, 0xd4, 0x1f, 0xf0, 0x18,
	0xdd, 0x83, 0x4d, 0x21, 0xdd, 0x1c, 0x51, 0x0b, 0xdb, 0xee, 0x77, 0x34, 0x1b, 0x3f, 0xa6, 0x72,
	0x3c, 0x08, 0x5b, 0x93, 0xe2, 0x29, 0xb5, 0x24, 0xf6, 0xa2, 0xbd, 0x71, 0x37, 0xf0, 0x70, 0xf6,
	0xf4, 0x31, 0xb7, 0x6b, 0xed, 0x3f, 0x83, 0x9b, 0x37, 0xd0, 0xbf, 0x68, 0x59, 0x0a, 0xe1, 0x02,
	0x0f, 0xd9, 0x95, 0x7b, 0xb9, 0x2d, 0xcb, 0x2c, 0x60, 0x43, 0x48, 0xef, 0x48, 0x55, 0xb5, 0x96,
	0x59, 0x8f, 0x01, 0x24, 0x1c, 0xab, 0xc6, 0x60, 0x16, 0xdd, 0xac, 0xba, 0xd8, 0xac, 0x0f, 0xd1,
	0x9a, 0x14, 0x66, 0x57, 0x6c, 0xd0, 0xdd, 0x73, 0x16, 0x38, 0xe6, 0xbd, 0xae, 0x51, 0x95, 0xad,
	0x6a, 0xa3, 0x0e, 0xb5, 0xc2, 0x2c, 0x74, 0x76, 0x9b, 0xaa, 0xf2, 0x20, 0x72, 0x07, 0xed, 0x46,
	0xb3, 0x78, 0x9e, 0x7c, 0x89, 0x5c, 0xb4, 0x6d, 0xe2, 0x7f, 0x82, 0x57, 0xbf, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x9f, 0xb7, 0x6a, 0x1d, 0x14, 0x03, 0x00, 0x00,
}
