// Code generated by protoc-gen-go.
// source: gate.proto
// DO NOT EDIT!

package meta

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GateFindUserRequest struct {
	User string `protobuf:"bytes,1,opt,name=User,json=user" json:"User,omitempty"`
}

func (m *GateFindUserRequest) Reset()                    { *m = GateFindUserRequest{} }
func (m *GateFindUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GateFindUserRequest) ProtoMessage()               {}
func (*GateFindUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type GateFindUserResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Users  []string        `protobuf:"bytes,2,rep,name=users" json:"users,omitempty"`
}

func (m *GateFindUserResponse) Reset()                    { *m = GateFindUserResponse{} }
func (m *GateFindUserResponse) String() string            { return proto.CompactTextString(m) }
func (*GateFindUserResponse) ProtoMessage()               {}
func (*GateFindUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *GateFindUserResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GateAddFriendRequest struct {
	UserID  int64  `protobuf:"varint,1,opt,name=UserID,json=userID" json:"UserID,omitempty"`
	Confirm bool   `protobuf:"varint,2,opt,name=Confirm,json=confirm" json:"Confirm,omitempty"`
	Msg     string `protobuf:"bytes,3,opt,name=Msg,json=msg" json:"Msg,omitempty"`
}

func (m *GateAddFriendRequest) Reset()                    { *m = GateAddFriendRequest{} }
func (m *GateAddFriendRequest) String() string            { return proto.CompactTextString(m) }
func (*GateAddFriendRequest) ProtoMessage()               {}
func (*GateAddFriendRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type GateAddFriendResponse struct {
	Header  *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Confirm bool            `protobuf:"varint,2,opt,name=Confirm,json=confirm" json:"Confirm,omitempty"`
}

func (m *GateAddFriendResponse) Reset()                    { *m = GateAddFriendResponse{} }
func (m *GateAddFriendResponse) String() string            { return proto.CompactTextString(m) }
func (*GateAddFriendResponse) ProtoMessage()               {}
func (*GateAddFriendResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *GateAddFriendResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GateCreateGroupRequest struct {
	GroupName string `protobuf:"bytes,1,opt,name=GroupName,json=groupName" json:"GroupName,omitempty"`
}

func (m *GateCreateGroupRequest) Reset()                    { *m = GateCreateGroupRequest{} }
func (m *GateCreateGroupRequest) String() string            { return proto.CompactTextString(m) }
func (*GateCreateGroupRequest) ProtoMessage()               {}
func (*GateCreateGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type GateCreateGroupResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ID     int64           `protobuf:"varint,2,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *GateCreateGroupResponse) Reset()                    { *m = GateCreateGroupResponse{} }
func (m *GateCreateGroupResponse) String() string            { return proto.CompactTextString(m) }
func (*GateCreateGroupResponse) ProtoMessage()               {}
func (*GateCreateGroupResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *GateCreateGroupResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GateRegisterRequest struct {
	User     string `protobuf:"bytes,1,opt,name=User,json=user" json:"User,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,json=password" json:"Password,omitempty"`
}

func (m *GateRegisterRequest) Reset()                    { *m = GateRegisterRequest{} }
func (m *GateRegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*GateRegisterRequest) ProtoMessage()               {}
func (*GateRegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

type GateRegisterResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ID     int64           `protobuf:"varint,2,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *GateRegisterResponse) Reset()                    { *m = GateRegisterResponse{} }
func (m *GateRegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*GateRegisterResponse) ProtoMessage()               {}
func (*GateRegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *GateRegisterResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GateUpdateUserInfoRequest struct {
	User     string `protobuf:"bytes,1,opt,name=User,json=user" json:"User,omitempty"`
	NickName string `protobuf:"bytes,2,opt,name=NickName,json=nickName" json:"NickName,omitempty"`
	Avatar   []byte `protobuf:"bytes,3,opt,name=Avatar,json=avatar,proto3" json:"Avatar,omitempty"`
}

func (m *GateUpdateUserInfoRequest) Reset()                    { *m = GateUpdateUserInfoRequest{} }
func (m *GateUpdateUserInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GateUpdateUserInfoRequest) ProtoMessage()               {}
func (*GateUpdateUserInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

type GateUpdateUserInfoResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ID     int64           `protobuf:"varint,2,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *GateUpdateUserInfoResponse) Reset()                    { *m = GateUpdateUserInfoResponse{} }
func (m *GateUpdateUserInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*GateUpdateUserInfoResponse) ProtoMessage()               {}
func (*GateUpdateUserInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *GateUpdateUserInfoResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GateUpdateUserPasswordRequest struct {
	User     string `protobuf:"bytes,1,opt,name=User,json=user" json:"User,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,json=password" json:"Password,omitempty"`
}

func (m *GateUpdateUserPasswordRequest) Reset()                    { *m = GateUpdateUserPasswordRequest{} }
func (m *GateUpdateUserPasswordRequest) String() string            { return proto.CompactTextString(m) }
func (*GateUpdateUserPasswordRequest) ProtoMessage()               {}
func (*GateUpdateUserPasswordRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

type GateUpdateUserPasswordResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ID     int64           `protobuf:"varint,2,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *GateUpdateUserPasswordResponse) Reset()                    { *m = GateUpdateUserPasswordResponse{} }
func (m *GateUpdateUserPasswordResponse) String() string            { return proto.CompactTextString(m) }
func (*GateUpdateUserPasswordResponse) ProtoMessage()               {}
func (*GateUpdateUserPasswordResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *GateUpdateUserPasswordResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GateGetUserInfoRequest struct {
	// 0:用户名称   1：用户ID
	Type     int32  `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=UserName,json=userName" json:"UserName,omitempty"`
	UserID   int64  `protobuf:"varint,3,opt,name=UserID,json=userID" json:"UserID,omitempty"`
}

func (m *GateGetUserInfoRequest) Reset()                    { *m = GateGetUserInfoRequest{} }
func (m *GateGetUserInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GateGetUserInfoRequest) ProtoMessage()               {}
func (*GateGetUserInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

type GateGetUserInfoResponse struct {
	Header   *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ID       int64           `protobuf:"varint,2,opt,name=ID,json=iD" json:"ID,omitempty"`
	User     string          `protobuf:"bytes,3,opt,name=User,json=user" json:"User,omitempty"`
	NickName string          `protobuf:"bytes,4,opt,name=NickName,json=nickName" json:"NickName,omitempty"`
	Avatar   []byte          `protobuf:"bytes,5,opt,name=Avatar,json=avatar,proto3" json:"Avatar,omitempty"`
}

func (m *GateGetUserInfoResponse) Reset()                    { *m = GateGetUserInfoResponse{} }
func (m *GateGetUserInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*GateGetUserInfoResponse) ProtoMessage()               {}
func (*GateGetUserInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *GateGetUserInfoResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GateHeartbeatRequest struct {
}

func (m *GateHeartbeatRequest) Reset()                    { *m = GateHeartbeatRequest{} }
func (m *GateHeartbeatRequest) String() string            { return proto.CompactTextString(m) }
func (*GateHeartbeatRequest) ProtoMessage()               {}
func (*GateHeartbeatRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

type GateHeartbeatResponse struct {
}

func (m *GateHeartbeatResponse) Reset()                    { *m = GateHeartbeatResponse{} }
func (m *GateHeartbeatResponse) String() string            { return proto.CompactTextString(m) }
func (*GateHeartbeatResponse) ProtoMessage()               {}
func (*GateHeartbeatResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

type GateUserLoginRequest struct {
	User     string `protobuf:"bytes,1,opt,name=User,json=user" json:"User,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,json=password" json:"Password,omitempty"`
}

func (m *GateUserLoginRequest) Reset()                    { *m = GateUserLoginRequest{} }
func (m *GateUserLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*GateUserLoginRequest) ProtoMessage()               {}
func (*GateUserLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

type GateUserLoginResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ID     int64           `protobuf:"varint,2,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *GateUserLoginResponse) Reset()                    { *m = GateUserLoginResponse{} }
func (m *GateUserLoginResponse) String() string            { return proto.CompactTextString(m) }
func (*GateUserLoginResponse) ProtoMessage()               {}
func (*GateUserLoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *GateUserLoginResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GateUserLogoutRequest struct {
}

func (m *GateUserLogoutRequest) Reset()                    { *m = GateUserLogoutRequest{} }
func (m *GateUserLogoutRequest) String() string            { return proto.CompactTextString(m) }
func (*GateUserLogoutRequest) ProtoMessage()               {}
func (*GateUserLogoutRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

type GateUserLogoutResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *GateUserLogoutResponse) Reset()                    { *m = GateUserLogoutResponse{} }
func (m *GateUserLogoutResponse) String() string            { return proto.CompactTextString(m) }
func (*GateUserLogoutResponse) ProtoMessage()               {}
func (*GateUserLogoutResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

func (m *GateUserLogoutResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GateUploadFileRequest struct {
	File []byte `protobuf:"bytes,1,opt,name=File,json=file,proto3" json:"File,omitempty"`
}

func (m *GateUploadFileRequest) Reset()                    { *m = GateUploadFileRequest{} }
func (m *GateUploadFileRequest) String() string            { return proto.CompactTextString(m) }
func (*GateUploadFileRequest) ProtoMessage()               {}
func (*GateUploadFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

type GateUploadFileResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *GateUploadFileResponse) Reset()                    { *m = GateUploadFileResponse{} }
func (m *GateUploadFileResponse) String() string            { return proto.CompactTextString(m) }
func (*GateUploadFileResponse) ProtoMessage()               {}
func (*GateUploadFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{21} }

func (m *GateUploadFileResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GateCheckFileRequest struct {
	Names []string `protobuf:"bytes,1,rep,name=Names,json=names" json:"Names,omitempty"`
}

func (m *GateCheckFileRequest) Reset()                    { *m = GateCheckFileRequest{} }
func (m *GateCheckFileRequest) String() string            { return proto.CompactTextString(m) }
func (*GateCheckFileRequest) ProtoMessage()               {}
func (*GateCheckFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{22} }

type GateCheckFileResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=Header,json=header" json:"Header,omitempty"`
	Names  []string        `protobuf:"bytes,2,rep,name=Names,json=names" json:"Names,omitempty"`
}

func (m *GateCheckFileResponse) Reset()                    { *m = GateCheckFileResponse{} }
func (m *GateCheckFileResponse) String() string            { return proto.CompactTextString(m) }
func (*GateCheckFileResponse) ProtoMessage()               {}
func (*GateCheckFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{23} }

func (m *GateCheckFileResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GateDownloadFileRequest struct {
	Names []string `protobuf:"bytes,1,rep,name=Names,json=names" json:"Names,omitempty"`
}

func (m *GateDownloadFileRequest) Reset()                    { *m = GateDownloadFileRequest{} }
func (m *GateDownloadFileRequest) String() string            { return proto.CompactTextString(m) }
func (*GateDownloadFileRequest) ProtoMessage()               {}
func (*GateDownloadFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{24} }

type GateDownloadFileResponse struct {
	Header *ResponseHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Files  map[string][]byte `protobuf:"bytes,2,rep,name=Files,json=files" json:"Files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *GateDownloadFileResponse) Reset()                    { *m = GateDownloadFileResponse{} }
func (m *GateDownloadFileResponse) String() string            { return proto.CompactTextString(m) }
func (*GateDownloadFileResponse) ProtoMessage()               {}
func (*GateDownloadFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{25} }

func (m *GateDownloadFileResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GateDownloadFileResponse) GetFiles() map[string][]byte {
	if m != nil {
		return m.Files
	}
	return nil
}

type GateNoticeRequest struct {
	ID  []*PushID `protobuf:"bytes,1,rep,name=ID,json=iD" json:"ID,omitempty"`
	Msg *Message  `protobuf:"bytes,2,opt,name=Msg,json=msg" json:"Msg,omitempty"`
}

func (m *GateNoticeRequest) Reset()                    { *m = GateNoticeRequest{} }
func (m *GateNoticeRequest) String() string            { return proto.CompactTextString(m) }
func (*GateNoticeRequest) ProtoMessage()               {}
func (*GateNoticeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{26} }

func (m *GateNoticeRequest) GetID() []*PushID {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *GateNoticeRequest) GetMsg() *Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

type GateNoticeResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *GateNoticeResponse) Reset()                    { *m = GateNoticeResponse{} }
func (m *GateNoticeResponse) String() string            { return proto.CompactTextString(m) }
func (*GateNoticeResponse) ProtoMessage()               {}
func (*GateNoticeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{27} }

func (m *GateNoticeResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GateLoadMessageRequest struct {
	ID      int64 `protobuf:"varint,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	Reverse bool  `protobuf:"varint,2,opt,name=Reverse,json=reverse" json:"Reverse,omitempty"`
}

func (m *GateLoadMessageRequest) Reset()                    { *m = GateLoadMessageRequest{} }
func (m *GateLoadMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*GateLoadMessageRequest) ProtoMessage()               {}
func (*GateLoadMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{28} }

type GateLoadMessageResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Msgs   []*Message      `protobuf:"bytes,2,rep,name=Msgs,json=msgs" json:"Msgs,omitempty"`
}

func (m *GateLoadMessageResponse) Reset()                    { *m = GateLoadMessageResponse{} }
func (m *GateLoadMessageResponse) String() string            { return proto.CompactTextString(m) }
func (*GateLoadMessageResponse) ProtoMessage()               {}
func (*GateLoadMessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{29} }

func (m *GateLoadMessageResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GateLoadMessageResponse) GetMsgs() []*Message {
	if m != nil {
		return m.Msgs
	}
	return nil
}

type GateLoadGroupListRequest struct {
}

func (m *GateLoadGroupListRequest) Reset()                    { *m = GateLoadGroupListRequest{} }
func (m *GateLoadGroupListRequest) String() string            { return proto.CompactTextString(m) }
func (*GateLoadGroupListRequest) ProtoMessage()               {}
func (*GateLoadGroupListRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{30} }

type GateLoadGroupListResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Groups []*Group        `protobuf:"bytes,2,rep,name=groups" json:"groups,omitempty"`
}

func (m *GateLoadGroupListResponse) Reset()                    { *m = GateLoadGroupListResponse{} }
func (m *GateLoadGroupListResponse) String() string            { return proto.CompactTextString(m) }
func (*GateLoadGroupListResponse) ProtoMessage()               {}
func (*GateLoadGroupListResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{31} }

func (m *GateLoadGroupListResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GateLoadGroupListResponse) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type GateLoadFriendListRequest struct {
}

func (m *GateLoadFriendListRequest) Reset()                    { *m = GateLoadFriendListRequest{} }
func (m *GateLoadFriendListRequest) String() string            { return proto.CompactTextString(m) }
func (*GateLoadFriendListRequest) ProtoMessage()               {}
func (*GateLoadFriendListRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{32} }

type GateLoadFriendListResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Users  []int64         `protobuf:"varint,2,rep,packed,name=users" json:"users,omitempty"`
}

func (m *GateLoadFriendListResponse) Reset()                    { *m = GateLoadFriendListResponse{} }
func (m *GateLoadFriendListResponse) String() string            { return proto.CompactTextString(m) }
func (*GateLoadFriendListResponse) ProtoMessage()               {}
func (*GateLoadFriendListResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{33} }

func (m *GateLoadFriendListResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GateSendMessageRequest struct {
	Msg *Message `protobuf:"bytes,1,opt,name=Msg,json=msg" json:"Msg,omitempty"`
}

func (m *GateSendMessageRequest) Reset()                    { *m = GateSendMessageRequest{} }
func (m *GateSendMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*GateSendMessageRequest) ProtoMessage()               {}
func (*GateSendMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{34} }

func (m *GateSendMessageRequest) GetMsg() *Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

type GateSendMessageResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Id     int64           `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
}

func (m *GateSendMessageResponse) Reset()                    { *m = GateSendMessageResponse{} }
func (m *GateSendMessageResponse) String() string            { return proto.CompactTextString(m) }
func (*GateSendMessageResponse) ProtoMessage()               {}
func (*GateSendMessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{35} }

func (m *GateSendMessageResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*GateFindUserRequest)(nil), "candy.meta.GateFindUserRequest")
	proto.RegisterType((*GateFindUserResponse)(nil), "candy.meta.GateFindUserResponse")
	proto.RegisterType((*GateAddFriendRequest)(nil), "candy.meta.GateAddFriendRequest")
	proto.RegisterType((*GateAddFriendResponse)(nil), "candy.meta.GateAddFriendResponse")
	proto.RegisterType((*GateCreateGroupRequest)(nil), "candy.meta.GateCreateGroupRequest")
	proto.RegisterType((*GateCreateGroupResponse)(nil), "candy.meta.GateCreateGroupResponse")
	proto.RegisterType((*GateRegisterRequest)(nil), "candy.meta.GateRegisterRequest")
	proto.RegisterType((*GateRegisterResponse)(nil), "candy.meta.GateRegisterResponse")
	proto.RegisterType((*GateUpdateUserInfoRequest)(nil), "candy.meta.GateUpdateUserInfoRequest")
	proto.RegisterType((*GateUpdateUserInfoResponse)(nil), "candy.meta.GateUpdateUserInfoResponse")
	proto.RegisterType((*GateUpdateUserPasswordRequest)(nil), "candy.meta.GateUpdateUserPasswordRequest")
	proto.RegisterType((*GateUpdateUserPasswordResponse)(nil), "candy.meta.GateUpdateUserPasswordResponse")
	proto.RegisterType((*GateGetUserInfoRequest)(nil), "candy.meta.GateGetUserInfoRequest")
	proto.RegisterType((*GateGetUserInfoResponse)(nil), "candy.meta.GateGetUserInfoResponse")
	proto.RegisterType((*GateHeartbeatRequest)(nil), "candy.meta.GateHeartbeatRequest")
	proto.RegisterType((*GateHeartbeatResponse)(nil), "candy.meta.GateHeartbeatResponse")
	proto.RegisterType((*GateUserLoginRequest)(nil), "candy.meta.GateUserLoginRequest")
	proto.RegisterType((*GateUserLoginResponse)(nil), "candy.meta.GateUserLoginResponse")
	proto.RegisterType((*GateUserLogoutRequest)(nil), "candy.meta.GateUserLogoutRequest")
	proto.RegisterType((*GateUserLogoutResponse)(nil), "candy.meta.GateUserLogoutResponse")
	proto.RegisterType((*GateUploadFileRequest)(nil), "candy.meta.GateUploadFileRequest")
	proto.RegisterType((*GateUploadFileResponse)(nil), "candy.meta.GateUploadFileResponse")
	proto.RegisterType((*GateCheckFileRequest)(nil), "candy.meta.GateCheckFileRequest")
	proto.RegisterType((*GateCheckFileResponse)(nil), "candy.meta.GateCheckFileResponse")
	proto.RegisterType((*GateDownloadFileRequest)(nil), "candy.meta.GateDownloadFileRequest")
	proto.RegisterType((*GateDownloadFileResponse)(nil), "candy.meta.GateDownloadFileResponse")
	proto.RegisterType((*GateNoticeRequest)(nil), "candy.meta.GateNoticeRequest")
	proto.RegisterType((*GateNoticeResponse)(nil), "candy.meta.GateNoticeResponse")
	proto.RegisterType((*GateLoadMessageRequest)(nil), "candy.meta.GateLoadMessageRequest")
	proto.RegisterType((*GateLoadMessageResponse)(nil), "candy.meta.GateLoadMessageResponse")
	proto.RegisterType((*GateLoadGroupListRequest)(nil), "candy.meta.GateLoadGroupListRequest")
	proto.RegisterType((*GateLoadGroupListResponse)(nil), "candy.meta.GateLoadGroupListResponse")
	proto.RegisterType((*GateLoadFriendListRequest)(nil), "candy.meta.GateLoadFriendListRequest")
	proto.RegisterType((*GateLoadFriendListResponse)(nil), "candy.meta.GateLoadFriendListResponse")
	proto.RegisterType((*GateSendMessageRequest)(nil), "candy.meta.GateSendMessageRequest")
	proto.RegisterType((*GateSendMessageResponse)(nil), "candy.meta.GateSendMessageResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Gate service

type GateClient interface {
	Register(ctx context.Context, in *GateRegisterRequest, opts ...grpc.CallOption) (*GateRegisterResponse, error)
	UpdateUserInfo(ctx context.Context, in *GateUpdateUserInfoRequest, opts ...grpc.CallOption) (*GateUpdateUserInfoResponse, error)
	UpdateUserPassword(ctx context.Context, in *GateUpdateUserPasswordRequest, opts ...grpc.CallOption) (*GateUpdateUserPasswordResponse, error)
	GetUserInfo(ctx context.Context, in *GateGetUserInfoRequest, opts ...grpc.CallOption) (*GateGetUserInfoResponse, error)
	Login(ctx context.Context, in *GateUserLoginRequest, opts ...grpc.CallOption) (*GateUserLoginResponse, error)
	Logout(ctx context.Context, in *GateUserLogoutRequest, opts ...grpc.CallOption) (*GateUserLogoutResponse, error)
	// SendMessage 发送消息
	SendMessage(ctx context.Context, in *GateSendMessageRequest, opts ...grpc.CallOption) (*GateSendMessageResponse, error)
	// Ready 连接成功后立刻调用Ready, 开启推送
	Ready(ctx context.Context, in *Message, opts ...grpc.CallOption) (Gate_ReadyClient, error)
	// AddFriend 添加好友或确认接受添加.
	AddFriend(ctx context.Context, in *GateAddFriendRequest, opts ...grpc.CallOption) (*GateAddFriendResponse, error)
	// FindUser 添加好友前先查找出来对应的ID.
	FindUser(ctx context.Context, in *GateFindUserRequest, opts ...grpc.CallOption) (*GateFindUserResponse, error)
	// 加载好友列表
	LoadFriendList(ctx context.Context, in *GateLoadFriendListRequest, opts ...grpc.CallOption) (*GateLoadFriendListResponse, error)
	CreateGroup(ctx context.Context, in *GateCreateGroupRequest, opts ...grpc.CallOption) (*GateCreateGroupResponse, error)
	// LoadGroupList 加载群组列表
	LoadGroupList(ctx context.Context, in *GateLoadGroupListRequest, opts ...grpc.CallOption) (*GateLoadGroupListResponse, error)
	Heartbeat(ctx context.Context, in *GateHeartbeatRequest, opts ...grpc.CallOption) (*GateHeartbeatResponse, error)
	// UploadFile 客户端上传文件接口，一次一个图片.
	UploadFile(ctx context.Context, in *GateUploadFileRequest, opts ...grpc.CallOption) (*GateUploadFileResponse, error)
	// CheckFile 客户端检测文件是否存在，文件的临时ID和md5, 服务器返回不存在的文件ID.
	CheckFile(ctx context.Context, in *GateCheckFileRequest, opts ...grpc.CallOption) (*GateCheckFileResponse, error)
	// DownloadFile 客户端下载文件，传入ID，返回具体文件内容.
	DownloadFile(ctx context.Context, in *GateDownloadFileRequest, opts ...grpc.CallOption) (*GateDownloadFileResponse, error)
	// ID 参照消息ID，每次可逆序(旧消息)或正序(新消息)接收100条
	// 如果ID为0，就逆序返回旧的100条消息
	LoadMessage(ctx context.Context, in *GateLoadMessageRequest, opts ...grpc.CallOption) (*GateLoadMessageResponse, error)
	// Notice 服务端向客户端推送接口.
	Notice(ctx context.Context, in *GateNoticeRequest, opts ...grpc.CallOption) (*GateNoticeResponse, error)
}

type gateClient struct {
	cc *grpc.ClientConn
}

func NewGateClient(cc *grpc.ClientConn) GateClient {
	return &gateClient{cc}
}

func (c *gateClient) Register(ctx context.Context, in *GateRegisterRequest, opts ...grpc.CallOption) (*GateRegisterResponse, error) {
	out := new(GateRegisterResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) UpdateUserInfo(ctx context.Context, in *GateUpdateUserInfoRequest, opts ...grpc.CallOption) (*GateUpdateUserInfoResponse, error) {
	out := new(GateUpdateUserInfoResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/UpdateUserInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) UpdateUserPassword(ctx context.Context, in *GateUpdateUserPasswordRequest, opts ...grpc.CallOption) (*GateUpdateUserPasswordResponse, error) {
	out := new(GateUpdateUserPasswordResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/UpdateUserPassword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) GetUserInfo(ctx context.Context, in *GateGetUserInfoRequest, opts ...grpc.CallOption) (*GateGetUserInfoResponse, error) {
	out := new(GateGetUserInfoResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/GetUserInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) Login(ctx context.Context, in *GateUserLoginRequest, opts ...grpc.CallOption) (*GateUserLoginResponse, error) {
	out := new(GateUserLoginResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) Logout(ctx context.Context, in *GateUserLogoutRequest, opts ...grpc.CallOption) (*GateUserLogoutResponse, error) {
	out := new(GateUserLogoutResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/Logout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) SendMessage(ctx context.Context, in *GateSendMessageRequest, opts ...grpc.CallOption) (*GateSendMessageResponse, error) {
	out := new(GateSendMessageResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/SendMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) Ready(ctx context.Context, in *Message, opts ...grpc.CallOption) (Gate_ReadyClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Gate_serviceDesc.Streams[0], c.cc, "/candy.meta.Gate/Ready", opts...)
	if err != nil {
		return nil, err
	}
	x := &gateReadyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Gate_ReadyClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type gateReadyClient struct {
	grpc.ClientStream
}

func (x *gateReadyClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gateClient) AddFriend(ctx context.Context, in *GateAddFriendRequest, opts ...grpc.CallOption) (*GateAddFriendResponse, error) {
	out := new(GateAddFriendResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/AddFriend", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) FindUser(ctx context.Context, in *GateFindUserRequest, opts ...grpc.CallOption) (*GateFindUserResponse, error) {
	out := new(GateFindUserResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/FindUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) LoadFriendList(ctx context.Context, in *GateLoadFriendListRequest, opts ...grpc.CallOption) (*GateLoadFriendListResponse, error) {
	out := new(GateLoadFriendListResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/LoadFriendList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) CreateGroup(ctx context.Context, in *GateCreateGroupRequest, opts ...grpc.CallOption) (*GateCreateGroupResponse, error) {
	out := new(GateCreateGroupResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/CreateGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) LoadGroupList(ctx context.Context, in *GateLoadGroupListRequest, opts ...grpc.CallOption) (*GateLoadGroupListResponse, error) {
	out := new(GateLoadGroupListResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/LoadGroupList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) Heartbeat(ctx context.Context, in *GateHeartbeatRequest, opts ...grpc.CallOption) (*GateHeartbeatResponse, error) {
	out := new(GateHeartbeatResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/Heartbeat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) UploadFile(ctx context.Context, in *GateUploadFileRequest, opts ...grpc.CallOption) (*GateUploadFileResponse, error) {
	out := new(GateUploadFileResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/UploadFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) CheckFile(ctx context.Context, in *GateCheckFileRequest, opts ...grpc.CallOption) (*GateCheckFileResponse, error) {
	out := new(GateCheckFileResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/CheckFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) DownloadFile(ctx context.Context, in *GateDownloadFileRequest, opts ...grpc.CallOption) (*GateDownloadFileResponse, error) {
	out := new(GateDownloadFileResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/DownloadFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) LoadMessage(ctx context.Context, in *GateLoadMessageRequest, opts ...grpc.CallOption) (*GateLoadMessageResponse, error) {
	out := new(GateLoadMessageResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/LoadMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) Notice(ctx context.Context, in *GateNoticeRequest, opts ...grpc.CallOption) (*GateNoticeResponse, error) {
	out := new(GateNoticeResponse)
	err := grpc.Invoke(ctx, "/candy.meta.Gate/Notice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Gate service

type GateServer interface {
	Register(context.Context, *GateRegisterRequest) (*GateRegisterResponse, error)
	UpdateUserInfo(context.Context, *GateUpdateUserInfoRequest) (*GateUpdateUserInfoResponse, error)
	UpdateUserPassword(context.Context, *GateUpdateUserPasswordRequest) (*GateUpdateUserPasswordResponse, error)
	GetUserInfo(context.Context, *GateGetUserInfoRequest) (*GateGetUserInfoResponse, error)
	Login(context.Context, *GateUserLoginRequest) (*GateUserLoginResponse, error)
	Logout(context.Context, *GateUserLogoutRequest) (*GateUserLogoutResponse, error)
	// SendMessage 发送消息
	SendMessage(context.Context, *GateSendMessageRequest) (*GateSendMessageResponse, error)
	// Ready 连接成功后立刻调用Ready, 开启推送
	Ready(*Message, Gate_ReadyServer) error
	// AddFriend 添加好友或确认接受添加.
	AddFriend(context.Context, *GateAddFriendRequest) (*GateAddFriendResponse, error)
	// FindUser 添加好友前先查找出来对应的ID.
	FindUser(context.Context, *GateFindUserRequest) (*GateFindUserResponse, error)
	// 加载好友列表
	LoadFriendList(context.Context, *GateLoadFriendListRequest) (*GateLoadFriendListResponse, error)
	CreateGroup(context.Context, *GateCreateGroupRequest) (*GateCreateGroupResponse, error)
	// LoadGroupList 加载群组列表
	LoadGroupList(context.Context, *GateLoadGroupListRequest) (*GateLoadGroupListResponse, error)
	Heartbeat(context.Context, *GateHeartbeatRequest) (*GateHeartbeatResponse, error)
	// UploadFile 客户端上传文件接口，一次一个图片.
	UploadFile(context.Context, *GateUploadFileRequest) (*GateUploadFileResponse, error)
	// CheckFile 客户端检测文件是否存在，文件的临时ID和md5, 服务器返回不存在的文件ID.
	CheckFile(context.Context, *GateCheckFileRequest) (*GateCheckFileResponse, error)
	// DownloadFile 客户端下载文件，传入ID，返回具体文件内容.
	DownloadFile(context.Context, *GateDownloadFileRequest) (*GateDownloadFileResponse, error)
	// ID 参照消息ID，每次可逆序(旧消息)或正序(新消息)接收100条
	// 如果ID为0，就逆序返回旧的100条消息
	LoadMessage(context.Context, *GateLoadMessageRequest) (*GateLoadMessageResponse, error)
	// Notice 服务端向客户端推送接口.
	Notice(context.Context, *GateNoticeRequest) (*GateNoticeResponse, error)
}

func RegisterGateServer(s *grpc.Server, srv GateServer) {
	s.RegisterService(&_Gate_serviceDesc, srv)
}

func _Gate_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).Register(ctx, req.(*GateRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_UpdateUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateUpdateUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).UpdateUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/UpdateUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).UpdateUserInfo(ctx, req.(*GateUpdateUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_UpdateUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateUpdateUserPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).UpdateUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/UpdateUserPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).UpdateUserPassword(ctx, req.(*GateUpdateUserPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateGetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).GetUserInfo(ctx, req.(*GateGetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateUserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).Login(ctx, req.(*GateUserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateUserLogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).Logout(ctx, req.(*GateUserLogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateSendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).SendMessage(ctx, req.(*GateSendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_Ready_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Message)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GateServer).Ready(m, &gateReadyServer{stream})
}

type Gate_ReadyServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type gateReadyServer struct {
	grpc.ServerStream
}

func (x *gateReadyServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _Gate_AddFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateAddFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).AddFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/AddFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).AddFriend(ctx, req.(*GateAddFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_FindUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateFindUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).FindUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/FindUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).FindUser(ctx, req.(*GateFindUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_LoadFriendList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateLoadFriendListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).LoadFriendList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/LoadFriendList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).LoadFriendList(ctx, req.(*GateLoadFriendListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateCreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).CreateGroup(ctx, req.(*GateCreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_LoadGroupList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateLoadGroupListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).LoadGroupList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/LoadGroupList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).LoadGroupList(ctx, req.(*GateLoadGroupListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).Heartbeat(ctx, req.(*GateHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateUploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/UploadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).UploadFile(ctx, req.(*GateUploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_CheckFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateCheckFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).CheckFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/CheckFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).CheckFile(ctx, req.(*GateCheckFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_DownloadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateDownloadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).DownloadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/DownloadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).DownloadFile(ctx, req.(*GateDownloadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_LoadMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateLoadMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).LoadMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/LoadMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).LoadMessage(ctx, req.(*GateLoadMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_Notice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateNoticeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).Notice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candy.meta.Gate/Notice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).Notice(ctx, req.(*GateNoticeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "candy.meta.Gate",
	HandlerType: (*GateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Gate_Register_Handler,
		},
		{
			MethodName: "UpdateUserInfo",
			Handler:    _Gate_UpdateUserInfo_Handler,
		},
		{
			MethodName: "UpdateUserPassword",
			Handler:    _Gate_UpdateUserPassword_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _Gate_GetUserInfo_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Gate_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Gate_Logout_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _Gate_SendMessage_Handler,
		},
		{
			MethodName: "AddFriend",
			Handler:    _Gate_AddFriend_Handler,
		},
		{
			MethodName: "FindUser",
			Handler:    _Gate_FindUser_Handler,
		},
		{
			MethodName: "LoadFriendList",
			Handler:    _Gate_LoadFriendList_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _Gate_CreateGroup_Handler,
		},
		{
			MethodName: "LoadGroupList",
			Handler:    _Gate_LoadGroupList_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Gate_Heartbeat_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _Gate_UploadFile_Handler,
		},
		{
			MethodName: "CheckFile",
			Handler:    _Gate_CheckFile_Handler,
		},
		{
			MethodName: "DownloadFile",
			Handler:    _Gate_DownloadFile_Handler,
		},
		{
			MethodName: "LoadMessage",
			Handler:    _Gate_LoadMessage_Handler,
		},
		{
			MethodName: "Notice",
			Handler:    _Gate_Notice_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Ready",
			Handler:       _Gate_Ready_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor1,
}

func init() { proto.RegisterFile("gate.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x58, 0x6d, 0x6f, 0xdb, 0x36,
	0x10, 0x86, 0xfc, 0x96, 0xf8, 0xe2, 0x05, 0x2b, 0x9b, 0x25, 0x9e, 0xb6, 0x76, 0x19, 0xdb, 0x6c,
	0xc9, 0x36, 0xb8, 0x43, 0x0a, 0x0c, 0xc5, 0xbe, 0x0c, 0x6d, 0x9c, 0x37, 0xc0, 0x4e, 0x0d, 0x15,
	0x2d, 0xb0, 0xee, 0xa5, 0x61, 0x2d, 0xc6, 0x11, 0x12, 0x4b, 0x9e, 0x28, 0xa7, 0xf0, 0xfe, 0xcf,
	0x7e, 0xcf, 0xbe, 0xec, 0x07, 0x0d, 0x7c, 0x91, 0x4d, 0x91, 0x92, 0x53, 0xc4, 0xfe, 0x12, 0xf8,
	0xa4, 0xe3, 0x3d, 0xc7, 0xbb, 0x47, 0xbc, 0x87, 0x01, 0x18, 0x90, 0x84, 0xb6, 0x46, 0x71, 0x94,
	0x44, 0x08, 0xfa, 0x24, 0xf4, 0x27, 0xad, 0x21, 0x4d, 0x88, 0xdb, 0xe8, 0x47, 0xc3, 0x61, 0x14,
	0xca, 0x37, 0x78, 0x0f, 0xee, 0x1f, 0x93, 0x84, 0x1e, 0x05, 0xa1, 0xff, 0x9a, 0xd1, 0xd8, 0xa3,
	0x7f, 0x8d, 0x29, 0x4b, 0x10, 0x82, 0x0a, 0x37, 0x9b, 0xce, 0xb6, 0xb3, 0x5b, 0xf7, 0x2a, 0x63,
	0x46, 0x63, 0x7c, 0x0e, 0x1b, 0x59, 0x57, 0x36, 0x8a, 0x42, 0x46, 0xd1, 0x3e, 0xd4, 0x2e, 0x29,
	0xf1, 0x95, 0xf7, 0xda, 0xbe, 0xdb, 0x9a, 0xa1, 0xb5, 0x52, 0xaf, 0x13, 0xe1, 0xe1, 0x29, 0x4f,
	0xb4, 0x01, 0x55, 0x1e, 0x93, 0x35, 0x4b, 0xdb, 0xe5, 0xdd, 0xba, 0x27, 0x0d, 0xfc, 0x56, 0x22,
	0x3c, 0xf7, 0xfd, 0xa3, 0x38, 0xa0, 0xa1, 0x9f, 0x66, 0xb3, 0x09, 0x35, 0x8e, 0x78, 0xda, 0x16,
	0x08, 0x65, 0xaf, 0x36, 0x16, 0x16, 0x6a, 0xc2, 0xca, 0x41, 0x14, 0x5e, 0x04, 0xf1, 0xb0, 0x59,
	0xda, 0x76, 0x76, 0x57, 0xbd, 0x95, 0xbe, 0x34, 0xd1, 0xa7, 0x50, 0xee, 0xb2, 0x41, 0xb3, 0x2c,
	0xd2, 0x2f, 0x0f, 0xd9, 0x00, 0x53, 0xf8, 0xcc, 0x88, 0xbd, 0x40, 0xfa, 0x85, 0xc0, 0xf8, 0x27,
	0xd8, 0xe4, 0x30, 0x07, 0x31, 0x25, 0x09, 0x3d, 0x8e, 0xa3, 0xf1, 0x28, 0xdd, 0xc4, 0x97, 0x50,
	0x17, 0xf6, 0x19, 0x19, 0x52, 0x55, 0xd7, 0xfa, 0x20, 0x7d, 0x80, 0xff, 0x80, 0x2d, 0x6b, 0xdd,
	0x02, 0x09, 0xae, 0x43, 0xe9, 0xb4, 0x2d, 0x72, 0x2b, 0x7b, 0xa5, 0xa0, 0x8d, 0x0f, 0x65, 0x9b,
	0x3d, 0x3a, 0x08, 0x58, 0x32, 0xb7, 0xcd, 0xc8, 0x85, 0xd5, 0x1e, 0x61, 0xec, 0x43, 0x14, 0xfb,
	0x22, 0x40, 0xdd, 0x5b, 0x1d, 0x29, 0x3b, 0x6d, 0xd0, 0x2c, 0xcc, 0x12, 0x53, 0xec, 0xc3, 0xe7,
	0x3c, 0xf6, 0xeb, 0x91, 0xcf, 0xff, 0xf2, 0x06, 0x87, 0x17, 0xd1, 0x2d, 0x89, 0x9e, 0x05, 0xfd,
	0x2b, 0x51, 0x4f, 0x95, 0x68, 0xa8, 0x6c, 0xce, 0x98, 0xe7, 0x37, 0x24, 0x21, 0xb1, 0xa0, 0x40,
	0xc3, 0xab, 0x11, 0x61, 0xe1, 0x73, 0x70, 0xf3, 0x40, 0x96, 0xb8, 0x8d, 0x97, 0xf0, 0x20, 0x8b,
	0x90, 0x16, 0xf3, 0xae, 0x35, 0xf7, 0xe1, 0x61, 0x51, 0xc0, 0x25, 0xa6, 0x7d, 0x2e, 0x79, 0x7b,
	0x4c, 0x93, 0x9c, 0xd2, 0x27, 0x93, 0x91, 0xa4, 0x6c, 0xd5, 0x13, 0xbf, 0x79, 0xbe, 0xdc, 0x4d,
	0x2f, 0xfd, 0x58, 0xd9, 0xda, 0xc7, 0x5a, 0xd6, 0x3f, 0x56, 0xfc, 0x8f, 0x23, 0x29, 0x9e, 0x81,
	0x58, 0xde, 0x0e, 0xa6, 0x75, 0x2d, 0x17, 0x50, 0xa4, 0x52, 0x48, 0x91, 0x6a, 0x86, 0x22, 0x9b,
	0x92, 0xe3, 0x27, 0x94, 0xc4, 0xc9, 0x7b, 0x4a, 0x12, 0x55, 0x07, 0xbc, 0x25, 0x0f, 0x10, 0xed,
	0xb9, 0x4c, 0x0b, 0x1f, 0xc9, 0x05, 0x1c, 0xbc, 0x13, 0x0d, 0x82, 0xf0, 0xae, 0x8d, 0xfe, 0x4d,
	0x02, 0x68, 0x71, 0x96, 0xd8, 0xdf, 0xad, 0x4c, 0xf0, 0x68, 0x3c, 0xdd, 0x56, 0x47, 0x36, 0x5e,
	0x7f, 0x71, 0x77, 0x58, 0xfc, 0xbd, 0x82, 0x19, 0x5d, 0x47, 0xc4, 0x3f, 0x0a, 0xae, 0xa9, 0x56,
	0x0c, 0x6e, 0x8a, 0x50, 0x0d, 0xaf, 0x72, 0x11, 0x5c, 0xd3, 0x29, 0xb4, 0xe6, 0xbc, 0x00, 0xf4,
	0x0f, 0xb2, 0x0d, 0x07, 0x97, 0xb4, 0x7f, 0xa5, 0x23, 0x6f, 0x40, 0x95, 0xf7, 0x9b, 0x35, 0x1d,
	0x39, 0x6a, 0x42, 0x6e, 0x60, 0x22, 0x13, 0xd5, 0xbc, 0x67, 0xd0, 0x27, 0x77, 0x98, 0x66, 0x12,
	0xa2, 0xa4, 0x43, 0x3c, 0x91, 0x7c, 0x6f, 0x47, 0x1f, 0x42, 0xb3, 0x1a, 0xf9, 0x39, 0xfd, 0xeb,
	0x40, 0xd3, 0x5e, 0xb1, 0x00, 0x09, 0x0e, 0xa1, 0xca, 0x63, 0xc8, 0xbc, 0xd6, 0xf6, 0x9f, 0xe8,
	0x4b, 0x8a, 0x80, 0x5a, 0x62, 0xc5, 0x61, 0x98, 0xc4, 0x13, 0xaf, 0xca, 0xdb, 0xc4, 0xdc, 0x67,
	0x00, 0xb3, 0x87, 0x7c, 0xb4, 0x5e, 0xd1, 0x89, 0x62, 0x35, 0xff, 0xc9, 0x77, 0x73, 0x43, 0xae,
	0xc7, 0xf2, 0x28, 0x68, 0x78, 0xd2, 0xf8, 0xb9, 0xf4, 0xcc, 0xc1, 0x7f, 0xc2, 0x3d, 0x8e, 0x73,
	0x16, 0x25, 0x41, 0x7f, 0xba, 0x79, 0x2c, 0xa8, 0xe9, 0x88, 0x94, 0x90, 0x9e, 0x52, 0x6f, 0xcc,
	0x2e, 0x4f, 0xdb, 0xe2, 0x63, 0xde, 0x91, 0xf3, 0xbb, 0x24, 0xb6, 0x7a, 0x5f, 0x77, 0xea, 0x52,
	0xc6, 0xc8, 0x80, 0xca, 0xa1, 0x7e, 0x02, 0x48, 0x8f, 0xbf, 0x00, 0x7b, 0x5e, 0x48, 0x2e, 0x76,
	0x22, 0xe2, 0xa7, 0x08, 0x2a, 0xdd, 0x75, 0x95, 0x6e, 0x7a, 0xce, 0x34, 0x61, 0xc5, 0xa3, 0x37,
	0x34, 0x66, 0x34, 0x9d, 0xfd, 0xb1, 0x34, 0xf1, 0x8d, 0x6c, 0x78, 0x26, 0xc6, 0x02, 0xdd, 0xfb,
	0x16, 0x2a, 0x5d, 0x36, 0x48, 0x9b, 0x97, 0x5b, 0x84, 0xca, 0x90, 0x0d, 0x18, 0x76, 0x25, 0x6d,
	0x38, 0xae, 0x50, 0x0e, 0x9d, 0x80, 0x4d, 0x3f, 0xef, 0xbf, 0xe5, 0x54, 0x35, 0xde, 0x2d, 0x90,
	0xd5, 0x1e, 0xd4, 0x84, 0x6a, 0x49, 0xf3, 0xba, 0x97, 0x21, 0x95, 0x10, 0x2e, 0xca, 0x01, 0x7f,
	0x31, 0xc3, 0x96, 0x9a, 0x4b, 0x4f, 0xec, 0x42, 0x4e, 0x62, 0xf3, 0xe5, 0xb2, 0x34, 0x65, 0x39,
	0xd5, 0x94, 0xbf, 0xc8, 0xc6, 0xbe, 0xa2, 0xa1, 0xd9, 0x58, 0xc5, 0x31, 0xe7, 0x16, 0x8e, 0x29,
	0x65, 0x96, 0x09, 0xb0, 0xd8, 0xc1, 0x1c, 0xf8, 0xd3, 0x83, 0xd9, 0xdf, 0xff, 0xaf, 0x01, 0x15,
	0x1e, 0x1f, 0x75, 0x61, 0x35, 0xd5, 0x55, 0xe8, 0x2b, 0xf3, 0x4b, 0x35, 0x84, 0x9b, 0xbb, 0x5d,
	0xec, 0xa0, 0x72, 0x7b, 0x07, 0xeb, 0x59, 0x95, 0x83, 0x76, 0xcc, 0x35, 0xb9, 0x52, 0xcb, 0xfd,
	0xe6, 0x36, 0x37, 0x05, 0x70, 0x05, 0xc8, 0xd6, 0x24, 0x68, 0xaf, 0x78, 0xb5, 0x21, 0x84, 0xdc,
	0xef, 0x3e, 0xc6, 0x55, 0x81, 0xbd, 0x81, 0x35, 0x4d, 0x37, 0x20, 0x6c, 0x2e, 0xb5, 0x75, 0x8b,
	0xfb, 0x68, 0xae, 0x8f, 0x8a, 0xdb, 0x81, 0xaa, 0x98, 0xb5, 0xc8, 0x2a, 0xa8, 0x39, 0xce, 0xdd,
	0xaf, 0xe7, 0x78, 0xa8, 0x68, 0x2f, 0xa1, 0x26, 0x67, 0x28, 0x2a, 0x72, 0x9e, 0x0d, 0x5e, 0x17,
	0xcf, 0x73, 0x99, 0x6d, 0x5b, 0xe3, 0x9d, 0xbd, 0x6d, 0x9b, 0xd5, 0xf6, 0xb6, 0xf3, 0x88, 0xfb,
	0x14, 0xaa, 0x1e, 0x25, 0xfe, 0x04, 0xe5, 0xd1, 0xde, 0xcd, 0x7b, 0xf8, 0xa3, 0x83, 0x7a, 0x50,
	0x9f, 0xde, 0x9e, 0xec, 0x7a, 0x99, 0x97, 0x36, 0xbb, 0x5e, 0xf6, 0xd5, 0xab, 0x0b, 0xab, 0xe9,
	0x6d, 0xd2, 0xa6, 0xbc, 0x71, 0x25, 0xb5, 0x29, 0x6f, 0x5d, 0x44, 0xdf, 0xc1, 0x7a, 0xf6, 0x38,
	0xb1, 0x29, 0x9f, 0x7b, 0x16, 0xd9, 0x94, 0x2f, 0x38, 0x95, 0xde, 0xc0, 0x9a, 0x76, 0x41, 0xb3,
	0xdb, 0x61, 0xdf, 0xfa, 0xec, 0x76, 0xe4, 0xdd, 0xf0, 0x7e, 0x87, 0x4f, 0x32, 0x07, 0x34, 0x7a,
	0x9c, 0x97, 0x90, 0x79, 0xb6, 0xbb, 0x3b, 0xb7, 0x78, 0xa9, 0xe8, 0x3d, 0xa8, 0x4f, 0x45, 0xab,
	0xdd, 0x37, 0x53, 0xe7, 0xda, 0x7d, 0xb3, 0x14, 0x2f, 0x7a, 0x05, 0x30, 0x13, 0x6d, 0x39, 0x5c,
	0x37, 0xd5, 0x5f, 0x0e, 0xd7, 0x6d, 0xcd, 0xd7, 0x83, 0xfa, 0x54, 0x8d, 0xd9, 0x69, 0x9a, 0xb2,
	0xce, 0x4e, 0xd3, 0x96, 0x72, 0xbf, 0x42, 0x43, 0x57, 0x38, 0xe8, 0xd1, 0x7c, 0xfd, 0x23, 0xe3,
	0x3e, 0xfe, 0x18, 0x91, 0xc4, 0x99, 0xa0, 0x8d, 0x79, 0x9b, 0x09, 0xb6, 0x8e, 0xb0, 0x99, 0x90,
	0xa7, 0x13, 0x8e, 0xa1, 0x26, 0xc5, 0x0c, 0x7a, 0x60, 0xba, 0x67, 0x44, 0x94, 0xfb, 0xb0, 0xe8,
	0xb5, 0x0c, 0xf4, 0xa2, 0xf6, 0xb6, 0xc2, 0x5f, 0xbd, 0xaf, 0x89, 0x7f, 0xf3, 0x3c, 0xfd, 0x3f,
	0x00, 0x00, 0xff, 0xff, 0x76, 0x19, 0x86, 0x40, 0x0e, 0x12, 0x00, 0x00,
}
